#!/usr/bin/python
# Copyright (C) 2008-2009 NAV CANADA (http://www.navcanada.ca)
# All rights reserved.
#
# This software is licensed as described in the file COPYING, which
# you should have received as part of this distribution.
#
# Author: Mike Stoddart <stoddam@navcanada.ca>
# Author: Jeff Dever <deverj@navcanada.ca>

from common import *

# Prompt for username.
username = prompt_username()

# Determine the list of projects to operate on.
if prompt_confirmation("Demote %s from administrator for all projects?" % username):
	project_list = get_project_list()
else:
	project_list = prompt_project_list()

# Promote the user the administrator as needed.
if not demote_user(username, project_list, VERIFY_USER_PERMISSIONS):
	print "Failed to demote user"
	sys.exit(-1)

#success
sys.exit(0)

