#
# ChangeLog for <?cs var:log.path ?> 
# 
# Generated by Trac <?cs var:trac.version ?>
# <?cs var:trac.time ?>
#
<?cs each:item = $log.items ?>
<?cs with:changeset = log.changes[item.rev] ?>
<?cs var:changeset.date ?> <?cs
     var:changeset.author ?> [<?cs var:item.rev ?>]<?cs
  set:idx = 0 ?><?cs
  each:file = changeset.files ?>
	* <?cs var:file ?> (<?cs
    set:action = changeset.actions[idx] ?><?cs
    if:action == 'add' ?>增加<?cs
    elif:action == 'delete' ?>删除<?cs
    elif:action == 'copy' ?>复制<?cs
    elif:action == 'move' ?>移动<?cs
    elif:action == 'edit' ?>修改<?cs
    /if ?>)<?cs
    set:idx = idx + 1 ?><?cs
  /each ?>
<?cs var:changeset.message ?><?cs 
  /with ?><?cs 
/each ?>
