#!/bin/sh

# POST-REVPROP-CHANGE HOOK
#
#   [1] REPOS-PATH   (the path to this repository)
#   [2] REV          (the revision that was tweaked)
#   [3] USER         (the username of the person tweaking the property)
#   [4] PROPNAME     (the property that was changed)
#   [5] ACTION       (the property was 'A'dded, 'M'odified, or 'D'eleted)
#
#   [STDIN] PROPVAL  ** the old property value is passed via STDIN.
#

REPOS="$1"
REV="$2"
USER="$3"
PROPNAME="$4"
ACTION="$5"
CONFIG_PATH=`dirname $0`

if [ -f "${CONFIG_PATH}/config" ]; then
  . ${CONFIG_PATH}/config
else
  echo "Missing config file" >&2
fi

REPOSNAME=`echo "$REPOS" | sed -r 's/^.*\/([^\/]+)$/\1/'`
TRAC_ENV="${TRAC_ENV_PARENT_DIR}/${REPOSNAME}"
LOGFILE="${TRAC_ENV}/log/svn-postrevpropchange.log"

export PYTHONPATH=$TRACPATH
date >> "$LOGFILE"
echo "Revprop: $REV $PROPNAME" >> $LOGFILE
${PYTHON} ${TRACPATH}/hooks/trac-revprop-hook -p "$TRAC_ENV" -u "$USER" \
    -n "$PROPNAME" -d "$REPOS" -r "$REV" -a "$ACTION" post 2>> "$LOGFILE"
if [ $? -ne 0 ]; then
    tail -5 "$LOGFILE" | \
      mail admin -s "[${REPOSNAME}] Unable to post-revprop revision ${REV}"
fi

