#!/bin/sh

# PRE-REVPROP-CHANGE HOOK
#
#   [1] REPOS-PATH   (the path to this repository)
#   [2] REVISION     (the revision being tweaked)
#   [3] USER         (the username of the person tweaking the property)
#   [4] PROPNAME     (the property being set on the revision)
#
#   [STDIN] PROPVAL  ** the new property value is passed via STDIN.

REPOS="$1"
REV="$2"
USER="$3"
PROPNAME="$4"
ACTION="$5"
CONFIG_PATH=`dirname $0`

if [ -f "${CONFIG_PATH}/config" ]; then
  . ${CONFIG_PATH}/config
else
  echo "Missing config file" >&2
fi

REPOSNAME=`echo "$REPOS" | sed -r 's/^.*\/([^\/]+)$/\1/'`
TRAC_ENV="${TRAC_ENV_PARENT_DIR}/${REPOSNAME}"
LOGFILE="${TRAC_ENV}/log/svn-prerevpropchange.log"

export PYTHONPATH=$TRACPATH
echo "Revprop: $REV $PROPNAME action:$ACTION" >> $LOGFILE
${PYTHON} ${TRACPATH}/hooks/trac-revprop-hook -p "$TRAC_ENV" -u "$USER" \
    -n "$PROPNAME" -d "$REPOS" -r "$REV" -a "$ACTION" pre 
RC=$?
echo "RESULT $RC" >>  $LOGFILE
[ $RC == 0 ] || exit 1

