[   [   (   1,
            u'task',
            1190909220000000L,
            1190909220000000L,
            u'',
            None,
            u'major',
            u'fd',
            u'testuser',
            u'',
            u'',
            u'Alpha 3_0',
            u'new',
            None,
            u'architecture > xc_archi > update lgen',
            u'',
            u''),
        (   2,
            u'task',
            1190909220000000L,
            1190909220000000L,
            u'',
            None,
            u'major',
            u'fd',
            u'testuser',
            u'',
            u'',
            u'Alpha 3_0',
            u'new',
            None,
            u'architecture > xc_archi > update netgen',
            u'',
            u''),
        (   3,
            u'task',
            1190909220000000L,
            1190909220000000L,
            u'',
            None,
            u'major',
            u'fd',
            u'testuser',
            u'',
            u'',
            u'Alpha 3_0',
            u'new',
            None,
            u'architecture > xc_archi > update adl (generate kad + dly + zan)',
            u'',
            u''),
        (   4,
            u'task',
            1190909220000000L,
            1190909220000000L,
            u'',
            None,
            u'major',
            u'fd',
            u'testuser',
            u'',
            u'',
            u'Alpha 3_0',
            u'new',
            None,
            u'architecture > xc_archi > modify traits',
            u'',
            u''),
        (   5,
            u'task',
            1190909220000000L,
            1190909220000000L,
            u'',
            None,
            u'major',
            u'pg',
            u'testuser',
            u'',
            u'',
            u'Alpha 3_0',
            u'new',
            None,
            u'architecture > test & integration > update lgen',
            u'',
            u''),
        (   6,
            u'task',
            1190909220000000L,
            1190909220000000L,
            u'',
            None,
            u'major',
            u'pg',
            u'testuser',
            u'',
            u'',
            u'Alpha 3_0',
            u'new',
            None,
            u'architecture > test & integration > update netgen',
            u'',
            u''),
        (   7,
            u'task',
            1190909220000000L,
            1190909220000000L,
            u'',
            None,
            u'major',
            u'pg',
            u'testuser',
            u'',
            u'',
            u'Alpha 3_0',
            u'new',
            None,
            u'architecture > test & integration > update adl (generate kad + dly + zan)',
            u'',
            u''),
        (   8,
            u'task',
            1190909220000000L,
            1190909220000000L,
            u'',
            None,
            u'major',
            u'pg',
            u'testuser',
            u'',
            u'',
            u'Alpha 3_0',
            u'new',
            None,
            u'architecture > test & integration > modify traits',
            u'',
            u''),
        (   9,
            u'task',
            1190909220000000L,
            1190909220000000L,
            u'',
            None,
            u'major',
            u'pg',
            u'testuser',
            u'',
            u'',
            u'Alpha 3_0',
            u'new',
            None,
            u'architecture > test & integration > update delay estimator for register file (adl)',
            u'',
            u''),
        (   10,
            u'task',
            1190909220000000L,
            1190909220000000L,
            u'',
            None,
            u'major',
            u'fd',
            u'testuser',
            u'',
            u'',
            u'Alpha 3_0',
            u'new',
            None,
            u'architecture > test & integration > update lgen',
            u'',
            u''),
        (   11,
            u'task',
            1190909220000000L,
            1190909220000000L,
            u'',
            None,
            u'major',
            u'fd',
            u'testuser',
            u'',
            u'',
            u'Alpha 3_0',
            u'new',
            None,
            u'architecture > test & integration > update netgen',
            u'',
            u''),
        (   12,
            u'task',
            1190909220000000L,
            1190909220000000L,
            u'',
            None,
            u'major',
            u'fd',
            u'testuser',
            u'',
            u'',
            u'Alpha 3_0',
            u'new',
            None,
            u'architecture > test & integration > update adl (generate kad + dly + zan)',
            u'',
            u''),
        (   13,
            u'task',
            1190909220000000L,
            1190909220000000L,
            u'',
            None,
            u'major',
            u'fd',
            u'testuser',
            u'',
            u'',
            u'Alpha 3_0',
            u'new',
            None,
            u'architecture > test & integration > modify traits',
            u'',
            u''),
        (   14,
            u'task',
            1190909220000000L,
            1190909220000000L,
            u'',
            None,
            u'major',
            u'pg',
            u'testuser',
            u'',
            u'',
            u'Alpha 3_0',
            u'new',
            None,
            u'zarkitek > time scale adjustment',
            u'',
            u''),
        (   15,
            u'task',
            1190909220000000L,
            1190909220000000L,
            u'',
            None,
            u'major',
            u'fd',
            u'testuser',
            u'',
            u'',
            u'Alpha 3_0',
            u'new',
            None,
            u'builder > introduce 18K ram',
            u'',
            u''),
        (   16,
            u'task',
            1190909220000000L,
            1190909220000000L,
            u'',
            None,
            u'major',
            u'fd',
            u'testuser',
            u'',
            u'',
            u'Alpha 3_0',
            u'new',
            None,
            u'builder > introduce regiser file',
            u'',
            u''),
        (   17,
            u'task',
            1190909220000000L,
            1190909220000000L,
            u'',
            None,
            u'major',
            u'fd',
            u'testuser',
            u'',
            u'',
            u'Alpha 3_0',
            u'new',
            None,
            u'builder > test & integration',
            u'',
            u''),
        (   18,
            u'task',
            1190909220000000L,
            1190909220000000L,
            u'',
            None,
            u'major',
            u'lj',
            u'testuser',
            u'',
            u'',
            u'Alpha 3_0',
            u'new',
            None,
            u'flat_place > dpram18k & register file in plugin',
            u'',
            u''),
        (   19,
            u'task',
            1190909220000000L,
            1190909220000000L,
            u'',
            None,
            u'major',
            u'lj',
            u'testuser',
            u'',
            u'',
            u'Alpha 3_0',
            u'new',
            None,
            u'flat_place > test & integration',
            u'',
            u''),
        (   20,
            u'task',
            1190909220000000L,
            1190909220000000L,
            u'',
            None,
            u'major',
            u'hc',
            u'testuser',
            u'',
            u'',
            u'Alpha 3_0',
            u'new',
            None,
            u'flat_route > dpram18k & register file integration > update plugin > orientate functions > implementation',
            u'',
            u''),
        (   21,
            u'task',
            1190909220000000L,
            1190909220000000L,
            u'',
            None,
            u'major',
            u'hc',
            u'testuser',
            u'',
            u'',
            u'Alpha 3_0',
            u'new',
            None,
            u'flat_route > dpram18k & register file integration > update plugin > orientate functions > test & integration',
            u'',
            u''),
        (   22,
            u'task',
            1190909220000000L,
            1190909220000000L,
            u'',
            None,
            u'major',
            u'hc',
            u'testuser',
            u'',
            u'',
            u'Alpha 3_0',
            u'new',
            None,
            u'flat_route > dpram18k & register file integration > update plugin > materialize functions > implementation v4x4',
            u'',
            u''),
        (   23,
            u'task',
            1190909220000000L,
            1190909220000000L,
            u'',
            None,
            u'major',
            u'hc',
            u'testuser',
            u'',
            u'',
            u'Alpha 3_0',
            u'new',
            None,
            u'flat_route > dpram18k & register file integration > update plugin > materialize functions > test & integration',
            u'',
            u''),
        (   24,
            u'task',
            1190909220000000L,
            1190909220000000L,
            u'',
            None,
            u'major',
            u'pg',
            u'testuser',
            u'',
            u'',
            u'Alpha 3_0',
            u'new',
            None,
            u'verification > 18K ram & regfile integration > update verilog model',
            u'',
            u''),
        (   25,
            u'task',
            1190909220000000L,
            1190909220000000L,
            u'',
            None,
            u'major',
            u'pg',
            u'testuser',
            u'',
            u'',
            u'Alpha 3_0',
            u'new',
            None,
            u'verification > 18K ram & regfile integration > simulation with verification model',
            u'',
            u''),
        (   26,
            u'task',
            1190909220000000L,
            1190909220000000L,
            u'',
            None,
            u'major',
            u'gs',
            u'testuser',
            u'',
            u'',
            u'Alpha 3_0',
            u'new',
            None,
            u'verification > 18K ram & regfile integration > update timming model (.lib)',
            u'',
            u''),
        (   27,
            u'task',
            1190909220000000L,
            1190909220000000L,
            u'',
            None,
            u'major',
            u'gs',
            u'testuser',
            u'',
            u'',
            u'Alpha 3_0',
            u'new',
            None,
            u'verification > 18K ram & regfile integration > update pluging ztv',
            u'',
            u''),
        (   28,
            u'task',
            1190909220000000L,
            1190909220000000L,
            u'',
            None,
            u'major',
            u'gs',
            u'testuser',
            u'',
            u'',
            u'Alpha 3_0',
            u'new',
            None,
            u'timing annalysis > enable_asynchonous_reset',
            u'',
            u''),
        (   29,
            u'task',
            1190909220000000L,
            1190909220000000L,
            u'',
            None,
            u'major',
            u'gs',
            u'testuser',
            u'',
            u'',
            u'Alpha 3_0',
            u'new',
            None,
            u'timing annalysis > asynchonous_path_domain',
            u'',
            u''),
        (   30,
            u'task',
            1190909220000000L,
            1190909220000000L,
            u'',
            None,
            u'major',
            u'gs',
            u'testuser',
            u'',
            u'',
            u'Alpha 3_0',
            u'new',
            None,
            u'timing annalysis > constrain > generated_clock',
            u'',
            u''),
        (   31,
            u'task',
            1190909220000000L,
            1190909220000000L,
            u'',
            None,
            u'major',
            u'gs',
            u'testuser',
            u'',
            u'',
            u'Alpha 3_0',
            u'new',
            None,
            u'timing annalysis > exception > subgraph extraction (no -through)',
            u'',
            u''),
        (   32,
            u'task',
            1190909220000000L,
            1190909220000000L,
            u'',
            None,
            u'major',
            u'gs',
            u'testuser',
            u'',
            u'',
            u'Alpha 3_0',
            u'new',
            None,
            u'timing annalysis > exception > false paths',
            u'',
            u''),
        (   33,
            u'task',
            1190909220000000L,
            1190909220000000L,
            u'',
            None,
            u'major',
            u'gs',
            u'testuser',
            u'',
            u'',
            u'Alpha 3_0',
            u'new',
            None,
            u'timing annalysis > exception > false path documentation',
            u'',
            u''),
        (   34,
            u'task',
            1190909220000000L,
            1190909220000000L,
            u'',
            None,
            u'major',
            u'gs',
            u'testuser',
            u'',
            u'',
            u'Alpha 3_0',
            u'new',
            None,
            u'timing annalysis > exception > multicycle paths',
            u'',
            u''),
        (   35,
            u'task',
            1190909220000000L,
            1190909220000000L,
            u'',
            None,
            u'major',
            u'gs',
            u'testuser',
            u'',
            u'',
            u'Alpha 3_0',
            u'new',
            None,
            u'timing annalysis > exception > min/max delay',
            u'',
            u''),
        (   36,
            u'task',
            1190909220000000L,
            1190909220000000L,
            u'',
            None,
            u'major',
            u'lj',
            u'testuser',
            u'',
            u'',
            u'Alpha 3_0',
            u'new',
            None,
            u'timing annalysis > transfer sdc a.p.i  to top_shell',
            u'',
            u''),
        (   37,
            u'task',
            1190909220000000L,
            1190909220000000L,
            u'',
            None,
            u'major',
            u'gs',
            u'testuser',
            u'',
            u'',
            u'Alpha 3_0',
            u'new',
            None,
            u'timing annalysis > transfer sdc a.p.i  to top_shell',
            u'',
            u''),
        (   38,
            u'task',
            1190909220000000L,
            1190909220000000L,
            u'',
            None,
            u'major',
            u'gs',
            u'testuser',
            u'',
            u'',
            u'Alpha 3_0',
            u'new',
            None,
            u'timing annalysis > add command',
            u'',
            u''),
        (   39,
            u'task',
            1190909220000000L,
            1190909220000000L,
            u'',
            None,
            u'major',
            u'gs',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'timing annalysis > test & integration',
            u'',
            u''),
        (   40,
            u'task',
            1190909220000000L,
            1190909220000000L,
            u'',
            None,
            u'major',
            u'ac',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'Optimization > clusterization',
            u'',
            u''),
        (   41,
            u'task',
            1190909220000000L,
            1190909220000000L,
            u'',
            None,
            u'major',
            u'lj',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'Optimization > clusterization',
            u'',
            u''),
        (   42,
            u'task',
            1190909220000000L,
            1190909220000000L,
            u'',
            None,
            u'major',
            u'ac',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'release > integration, quality & regression',
            u'',
            u''),
        (   43,
            u'task',
            1190909220000000L,
            1190909220000000L,
            u'',
            None,
            u'major',
            u'fd',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'release > integration, quality & regression',
            u'',
            u''),
        (   44,
            u'task',
            1190909220000000L,
            1190909220000000L,
            u'',
            None,
            u'major',
            u'gs',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'release > integration, quality & regression',
            u'',
            u''),
        (   45,
            u'task',
            1190909220000000L,
            1190909220000000L,
            u'',
            None,
            u'major',
            u'hc',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'release > integration, quality & regression',
            u'',
            u''),
        (   46,
            u'task',
            1190909220000000L,
            1190909220000000L,
            u'',
            None,
            u'major',
            u'lj',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'release > integration, quality & regression',
            u'',
            u''),
        (   47,
            u'task',
            1190909220000000L,
            1190909220000000L,
            u'',
            None,
            u'major',
            u'pg',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'release > integration, quality & regression',
            u'',
            u'')],
    [   (1, u'effort', u''),
        (2, u'effort', u''),
        (3, u'effort', u''),
        (4, u'effort', u''),
        (5, u'effort', u''),
        (6, u'effort', u''),
        (7, u'effort', u''),
        (8, u'effort', u''),
        (9, u'effort', u''),
        (10, u'effort', u''),
        (11, u'effort', u''),
        (12, u'effort', u''),
        (13, u'effort', u''),
        (14, u'effort', u''),
        (15, u'effort', u''),
        (16, u'effort', u''),
        (17, u'effort', u''),
        (18, u'effort', u''),
        (19, u'effort', u''),
        (20, u'effort', u''),
        (21, u'effort', u''),
        (22, u'effort', u''),
        (23, u'effort', u''),
        (24, u'effort', u''),
        (25, u'effort', u''),
        (26, u'effort', u''),
        (27, u'effort', u''),
        (28, u'effort', u''),
        (29, u'effort', u''),
        (30, u'effort', u''),
        (31, u'effort', u''),
        (32, u'effort', u''),
        (33, u'effort', u''),
        (34, u'effort', u''),
        (35, u'effort', u''),
        (36, u'effort', u''),
        (37, u'effort', u''),
        (38, u'effort', u''),
        (39, u'effort', u''),
        (40, u'effort', u''),
        (41, u'effort', u''),
        (42, u'effort', u''),
        (43, u'effort', u''),
        (44, u'effort', u''),
        (45, u'effort', u''),
        (46, u'effort', u''),
        (47, u'effort', u'')],
    [],
    [],
    []]