{   'headers': [   {'col': 'ticket', 'title': 'ticket'},
                   {'col': 'summary', 'title': 'Summary'},
                   {'col': 'component', 'title': 'Component'},
                   {'col': 'milestone', 'title': 'Milestone'}],
    'message': <Markup u'<style type="text/css">\n.ticket-imported, .modified-ticket-imported { width: 40px; }\n.color-new-odd td, .color-new-even td, .modified-ticket-imported, .modified-summary, .modified-component, .modified-milestone { font-style: italic; }\n</style>\n<p>\nScroll to see a preview of the tickets as they will be imported. If the data is correct, select the <strong>Execute Import</strong> button.\n</p>\n<ul><li>61 tickets will be imported (61 added, 0 modified, 0 unchanged).\n</li><li>A <strong>ticket</strong> column was not found: tickets will be reconciliated by summary. If an existing ticket with the same summary is found, values that are changing appear in italics in the preview below. If no ticket with same summary is found, the whole line appears in italics below, and a new ticket will be added.\n</li><li>Some Trac fields are not present in the import. They will default to:\n</li></ul><blockquote>\n<blockquote>\n<table class="wiki">\n<tr><td><strong>field</strong></td><td><strong>Default value</strong>\n</td></tr><tr><td>Description, Cc, Keywords, Version, Mycustomfield, Severity</td><td><i>(Empty value)</i>\n</td></tr><tr><td>Status</td><td>new\n</td></tr><tr><td>Changetime</td><td><i>(now)</i>\n</td></tr><tr><td>Reporter</td><td>testuser\n</td></tr><tr><td>Type</td><td>task\n</td></tr><tr><td>Priority</td><td>major\n</td></tr><tr><td>Time</td><td><i>(now)</i>\n</td></tr><tr><td>Owner</td><td>Computed from component\n</td></tr><tr><td>Resolution</td><td><i>(None)</i>\n</td></tr></table>\n</blockquote>\n</blockquote>\n<p>\n(You can change some of these default values in the Trac Admin module, if you are administrator; or you can add the corresponding column to your spreadsheet and re-upload it).\n</p>\n<ul><li>Some fields will not be imported because they don\'t exist in Trac: Dev, Initial, 5/4, 5/7, 5/8, 5/9, 5/10, 5/11, 5/14, 5/15, 5/16, 5/17, 5/18, 5/21, 5/22, 5/23, 5/24, 5/25, 5/28, 5/29, 5/30, 5/31, 6/1, 6/4, 6/5, 6/6, 6/7, 6/8, 6/11, 6/12, 6/13, 6/14, 6/15, 6/18, 6/19, 6/20, 6/21, 6/22, 6/25, 6/26, 6/27, 6/28, 6/29, 7/2, 7/3, 7/4, 7/5, 7/6, 7/9, 7/10, 7/11, 7/12, 7/13, 7/16, 7/17, 7/18, 7/19, 7/20, 7/23, 7/24.\n</li><li>Some lookup values are not found and will be added to the possible list of values:\n</li></ul><blockquote>\n<blockquote>\n<table class="wiki">\n<tr><td><strong>field</strong></td><td><strong>New values</strong>\n</td></tr><tr><td>Component</td><td>architecture, zarkitek, builder, flat_place, flat_route, verification, timing annalysis, Optimization, release\n</td></tr><tr><td>Milestone</td><td>Alpha 3_0\n</td></tr></table>\n</blockquote>\n</blockquote>\n<br/>'>,
    'rows': [   {   'cells': [   {   'col': 'ticket',
                                     'style': '',
                                     'value': '(new)'},
                                 {   'col': 'summary',
                                     'style': 'summary',
                                     'value': u'xc_archi'},
                                 {   'col': 'component',
                                     'style': 'component',
                                     'value': u'architecture'},
                                 {   'col': 'milestone',
                                     'style': 'milestone',
                                     'value': u'Alpha 3_0'}],
                    'style': 'color-new-even'},
                {   'cells': [   {   'col': 'ticket',
                                     'style': '',
                                     'value': '(new)'},
                                 {   'col': 'summary',
                                     'style': 'summary',
                                     'value': u'xc_archi > introduce register file'},
                                 {   'col': 'component',
                                     'style': 'component',
                                     'value': u'architecture'},
                                 {   'col': 'milestone',
                                     'style': 'milestone',
                                     'value': u'Alpha 3_0'}],
                    'style': 'color-new-odd'},
                {   'cells': [   {   'col': 'ticket',
                                     'style': '',
                                     'value': '(new)'},
                                 {   'col': 'summary',
                                     'style': 'summary',
                                     'value': u'xc_archi > introduce 18K ram'},
                                 {   'col': 'component',
                                     'style': 'component',
                                     'value': u'architecture'},
                                 {   'col': 'milestone',
                                     'style': 'milestone',
                                     'value': u'Alpha 3_0'}],
                    'style': 'color-new-even'},
                {   'cells': [   {   'col': 'ticket',
                                     'style': '',
                                     'value': '(new)'},
                                 {   'col': 'summary',
                                     'style': 'summary',
                                     'value': u'xc_archi > modify io blocs'},
                                 {   'col': 'component',
                                     'style': 'component',
                                     'value': u'architecture'},
                                 {   'col': 'milestone',
                                     'style': 'milestone',
                                     'value': u'Alpha 3_0'}],
                    'style': 'color-new-odd'},
                {   'cells': [   {   'col': 'ticket',
                                     'style': '',
                                     'value': '(new)'},
                                 {   'col': 'summary',
                                     'style': 'summary',
                                     'value': u'xc_archi > primitive library description'},
                                 {   'col': 'component',
                                     'style': 'component',
                                     'value': u'architecture'},
                                 {   'col': 'milestone',
                                     'style': 'milestone',
                                     'value': u'Alpha 3_0'}],
                    'style': 'color-new-even'},
                {   'cells': [   {   'col': 'ticket',
                                     'style': '',
                                     'value': '(new)'},
                                 {   'col': 'summary',
                                     'style': 'summary',
                                     'value': u'xc_archi > update lgen'},
                                 {   'col': 'component',
                                     'style': 'component',
                                     'value': u'architecture'},
                                 {   'col': 'milestone',
                                     'style': 'milestone',
                                     'value': u'Alpha 3_0'}],
                    'style': 'color-new-odd'},
                {   'cells': [   {   'col': 'ticket',
                                     'style': '',
                                     'value': '(new)'},
                                 {   'col': 'summary',
                                     'style': 'summary',
                                     'value': u'xc_archi > update netgen'},
                                 {   'col': 'component',
                                     'style': 'component',
                                     'value': u'architecture'},
                                 {   'col': 'milestone',
                                     'style': 'milestone',
                                     'value': u'Alpha 3_0'}],
                    'style': 'color-new-even'},
                {   'cells': [   {   'col': 'ticket',
                                     'style': '',
                                     'value': '(new)'},
                                 {   'col': 'summary',
                                     'style': 'summary',
                                     'value': u'xc_archi > update adl (generate kad + dly + zan)'},
                                 {   'col': 'component',
                                     'style': 'component',
                                     'value': u'architecture'},
                                 {   'col': 'milestone',
                                     'style': 'milestone',
                                     'value': u'Alpha 3_0'}],
                    'style': 'color-new-odd'},
                {   'cells': [   {   'col': 'ticket',
                                     'style': '',
                                     'value': '(new)'},
                                 {   'col': 'summary',
                                     'style': 'summary',
                                     'value': u'xc_archi > modify traits'},
                                 {   'col': 'component',
                                     'style': 'component',
                                     'value': u'architecture'},
                                 {   'col': 'milestone',
                                     'style': 'milestone',
                                     'value': u'Alpha 3_0'}],
                    'style': 'color-new-even'},
                {   'cells': [   {   'col': 'ticket',
                                     'style': '',
                                     'value': '(new)'},
                                 {   'col': 'summary',
                                     'style': 'summary',
                                     'value': u'test & integration'},
                                 {   'col': 'component',
                                     'style': 'component',
                                     'value': u'architecture'},
                                 {   'col': 'milestone',
                                     'style': 'milestone',
                                     'value': u'Alpha 3_0'}],
                    'style': 'color-new-odd'},
                {   'cells': [   {   'col': 'ticket',
                                     'style': '',
                                     'value': '(new)'},
                                 {   'col': 'summary',
                                     'style': 'summary',
                                     'value': u'test & integration > update lgen'},
                                 {   'col': 'component',
                                     'style': 'component',
                                     'value': u'architecture'},
                                 {   'col': 'milestone',
                                     'style': 'milestone',
                                     'value': u'Alpha 3_0'}],
                    'style': 'color-new-even'},
                {   'cells': [   {   'col': 'ticket',
                                     'style': '',
                                     'value': '(new)'},
                                 {   'col': 'summary',
                                     'style': 'summary',
                                     'value': u'test & integration > update netgen'},
                                 {   'col': 'component',
                                     'style': 'component',
                                     'value': u'architecture'},
                                 {   'col': 'milestone',
                                     'style': 'milestone',
                                     'value': u'Alpha 3_0'}],
                    'style': 'color-new-odd'},
                {   'cells': [   {   'col': 'ticket',
                                     'style': '',
                                     'value': '(new)'},
                                 {   'col': 'summary',
                                     'style': 'summary',
                                     'value': u'test & integration > update adl (generate kad + dly + zan)'},
                                 {   'col': 'component',
                                     'style': 'component',
                                     'value': u'architecture'},
                                 {   'col': 'milestone',
                                     'style': 'milestone',
                                     'value': u'Alpha 3_0'}],
                    'style': 'color-new-even'},
                {   'cells': [   {   'col': 'ticket',
                                     'style': '',
                                     'value': '(new)'},
                                 {   'col': 'summary',
                                     'style': 'summary',
                                     'value': u'test & integration > modify traits'},
                                 {   'col': 'component',
                                     'style': 'component',
                                     'value': u'architecture'},
                                 {   'col': 'milestone',
                                     'style': 'milestone',
                                     'value': u'Alpha 3_0'}],
                    'style': 'color-new-odd'},
                {   'cells': [   {   'col': 'ticket',
                                     'style': '',
                                     'value': '(new)'},
                                 {   'col': 'summary',
                                     'style': 'summary',
                                     'value': u'test & integration > update delay estimator for register file (adl)'},
                                 {   'col': 'component',
                                     'style': 'component',
                                     'value': u'architecture'},
                                 {   'col': 'milestone',
                                     'style': 'milestone',
                                     'value': u'Alpha 3_0'}],
                    'style': 'color-new-even'},
                {   'cells': [   {   'col': 'ticket',
                                     'style': '',
                                     'value': '(new)'},
                                 {   'col': 'summary',
                                     'style': 'summary',
                                     'value': u'test & integration 4'},
                                 {   'col': 'component',
                                     'style': 'component',
                                     'value': u'architecture'},
                                 {   'col': 'milestone',
                                     'style': 'milestone',
                                     'value': u'Alpha 3_0'}],
                    'style': 'color-new-odd'},
                {   'cells': [   {   'col': 'ticket',
                                     'style': '',
                                     'value': '(new)'},
                                 {   'col': 'summary',
                                     'style': 'summary',
                                     'value': u'test & integration > update lgen 2'},
                                 {   'col': 'component',
                                     'style': 'component',
                                     'value': u'architecture'},
                                 {   'col': 'milestone',
                                     'style': 'milestone',
                                     'value': u'Alpha 3_0'}],
                    'style': 'color-new-even'},
                {   'cells': [   {   'col': 'ticket',
                                     'style': '',
                                     'value': '(new)'},
                                 {   'col': 'summary',
                                     'style': 'summary',
                                     'value': u'test & integration > update netgen 2'},
                                 {   'col': 'component',
                                     'style': 'component',
                                     'value': u'architecture'},
                                 {   'col': 'milestone',
                                     'style': 'milestone',
                                     'value': u'Alpha 3_0'}],
                    'style': 'color-new-odd'},
                {   'cells': [   {   'col': 'ticket',
                                     'style': '',
                                     'value': '(new)'},
                                 {   'col': 'summary',
                                     'style': 'summary',
                                     'value': u'test & integration > update adl (generate kad + dly + zan) 2'},
                                 {   'col': 'component',
                                     'style': 'component',
                                     'value': u'architecture'},
                                 {   'col': 'milestone',
                                     'style': 'milestone',
                                     'value': u'Alpha 3_0'}],
                    'style': 'color-new-even'},
                {   'cells': [   {   'col': 'ticket',
                                     'style': '',
                                     'value': '(new)'},
                                 {   'col': 'summary',
                                     'style': 'summary',
                                     'value': u'test & integration > modify traits 2'},
                                 {   'col': 'component',
                                     'style': 'component',
                                     'value': u'architecture'},
                                 {   'col': 'milestone',
                                     'style': 'milestone',
                                     'value': u'Alpha 3_0'}],
                    'style': 'color-new-odd'},
                {   'cells': [   {   'col': 'ticket',
                                     'style': '',
                                     'value': '(new)'},
                                 {   'col': 'summary',
                                     'style': 'summary',
                                     'value': u'time scale adjustment'},
                                 {   'col': 'component',
                                     'style': 'component',
                                     'value': u'zarkitek'},
                                 {   'col': 'milestone',
                                     'style': 'milestone',
                                     'value': u'Alpha 3_0'}],
                    'style': 'color-new-even'},
                {   'cells': [   {   'col': 'ticket',
                                     'style': '',
                                     'value': '(new)'},
                                 {   'col': 'summary',
                                     'style': 'summary',
                                     'value': u'introduce 18K ram'},
                                 {   'col': 'component',
                                     'style': 'component',
                                     'value': u'builder'},
                                 {   'col': 'milestone',
                                     'style': 'milestone',
                                     'value': u'Alpha 3_0'}],
                    'style': 'color-new-odd'},
                {   'cells': [   {   'col': 'ticket',
                                     'style': '',
                                     'value': '(new)'},
                                 {   'col': 'summary',
                                     'style': 'summary',
                                     'value': u'introduce regiser file'},
                                 {   'col': 'component',
                                     'style': 'component',
                                     'value': u'builder'},
                                 {   'col': 'milestone',
                                     'style': 'milestone',
                                     'value': u'Alpha 3_0'}],
                    'style': 'color-new-even'},
                {   'cells': [   {   'col': 'ticket',
                                     'style': '',
                                     'value': '(new)'},
                                 {   'col': 'summary',
                                     'style': 'summary',
                                     'value': u'test & integration 2'},
                                 {   'col': 'component',
                                     'style': 'component',
                                     'value': u'builder'},
                                 {   'col': 'milestone',
                                     'style': 'milestone',
                                     'value': u'Alpha 3_0'}],
                    'style': 'color-new-odd'},
                {   'cells': [   {   'col': 'ticket',
                                     'style': '',
                                     'value': '(new)'},
                                 {   'col': 'summary',
                                     'style': 'summary',
                                     'value': u'dpram18k & register file in plugin'},
                                 {   'col': 'component',
                                     'style': 'component',
                                     'value': u'flat_place'},
                                 {   'col': 'milestone',
                                     'style': 'milestone',
                                     'value': u'Alpha 3_0'}],
                    'style': 'color-new-even'},
                {   'cells': [   {   'col': 'ticket',
                                     'style': '',
                                     'value': '(new)'},
                                 {   'col': 'summary',
                                     'style': 'summary',
                                     'value': u'test & integration 3'},
                                 {   'col': 'component',
                                     'style': 'component',
                                     'value': u'flat_place'},
                                 {   'col': 'milestone',
                                     'style': 'milestone',
                                     'value': u'Alpha 3_0'}],
                    'style': 'color-new-odd'},
                {   'cells': [   {   'col': 'ticket',
                                     'style': '',
                                     'value': '(new)'},
                                 {   'col': 'summary',
                                     'style': 'summary',
                                     'value': u'dpram18k & register file integration'},
                                 {   'col': 'component',
                                     'style': 'component',
                                     'value': u'flat_route'},
                                 {   'col': 'milestone',
                                     'style': 'milestone',
                                     'value': u'Alpha 3_0'}],
                    'style': 'color-new-even'},
                {   'cells': [   {   'col': 'ticket',
                                     'style': '',
                                     'value': '(new)'},
                                 {   'col': 'summary',
                                     'style': 'summary',
                                     'value': u'dpram18k & register file integration > update plugin'},
                                 {   'col': 'component',
                                     'style': 'component',
                                     'value': u'flat_route'},
                                 {   'col': 'milestone',
                                     'style': 'milestone',
                                     'value': u'Alpha 3_0'}],
                    'style': 'color-new-odd'},
                {   'cells': [   {   'col': 'ticket',
                                     'style': '',
                                     'value': '(new)'},
                                 {   'col': 'summary',
                                     'style': 'summary',
                                     'value': u'dpram18k & register file integration > update plugin > orientate functions'},
                                 {   'col': 'component',
                                     'style': 'component',
                                     'value': u'flat_route'},
                                 {   'col': 'milestone',
                                     'style': 'milestone',
                                     'value': u'Alpha 3_0'}],
                    'style': 'color-new-even'},
                {   'cells': [   {   'col': 'ticket',
                                     'style': '',
                                     'value': '(new)'},
                                 {   'col': 'summary',
                                     'style': 'summary',
                                     'value': u'dpram18k & register file integration > update plugin > orientate functions > implementation'},
                                 {   'col': 'component',
                                     'style': 'component',
                                     'value': u'flat_route'},
                                 {   'col': 'milestone',
                                     'style': 'milestone',
                                     'value': u'Alpha 3_0'}],
                    'style': 'color-new-odd'},
                {   'cells': [   {   'col': 'ticket',
                                     'style': '',
                                     'value': '(new)'},
                                 {   'col': 'summary',
                                     'style': 'summary',
                                     'value': u'dpram18k & register file integration > update plugin > orientate functions > test & integration'},
                                 {   'col': 'component',
                                     'style': 'component',
                                     'value': u'flat_route'},
                                 {   'col': 'milestone',
                                     'style': 'milestone',
                                     'value': u'Alpha 3_0'}],
                    'style': 'color-new-even'},
                {   'cells': [   {   'col': 'ticket',
                                     'style': '',
                                     'value': '(new)'},
                                 {   'col': 'summary',
                                     'style': 'summary',
                                     'value': u'dpram18k & register file integration > update plugin > materialize functions'},
                                 {   'col': 'component',
                                     'style': 'component',
                                     'value': u'flat_route'},
                                 {   'col': 'milestone',
                                     'style': 'milestone',
                                     'value': u'Alpha 3_0'}],
                    'style': 'color-new-odd'},
                {   'cells': [   {   'col': 'ticket',
                                     'style': '',
                                     'value': '(new)'},
                                 {   'col': 'summary',
                                     'style': 'summary',
                                     'value': u'dpram18k & register file integration > update plugin > materialize functions > implementation v4x4'},
                                 {   'col': 'component',
                                     'style': 'component',
                                     'value': u'flat_route'},
                                 {   'col': 'milestone',
                                     'style': 'milestone',
                                     'value': u'Alpha 3_0'}],
                    'style': 'color-new-even'},
                {   'cells': [   {   'col': 'ticket',
                                     'style': '',
                                     'value': '(new)'},
                                 {   'col': 'summary',
                                     'style': 'summary',
                                     'value': u'dpram18k & register file integration > update plugin > materialize functions > test & integration'},
                                 {   'col': 'component',
                                     'style': 'component',
                                     'value': u'flat_route'},
                                 {   'col': 'milestone',
                                     'style': 'milestone',
                                     'value': u'Alpha 3_0'}],
                    'style': 'color-new-odd'},
                {   'cells': [   {   'col': 'ticket',
                                     'style': '',
                                     'value': '(new)'},
                                 {   'col': 'summary',
                                     'style': 'summary',
                                     'value': u'18K ram & regfile integration'},
                                 {   'col': 'component',
                                     'style': 'component',
                                     'value': u'verification'},
                                 {   'col': 'milestone',
                                     'style': 'milestone',
                                     'value': u'Alpha 3_0'}],
                    'style': 'color-new-even'},
                {   'cells': [   {   'col': 'ticket',
                                     'style': '',
                                     'value': '(new)'},
                                 {   'col': 'summary',
                                     'style': 'summary',
                                     'value': u'18K ram & regfile integration > update verilog model'},
                                 {   'col': 'component',
                                     'style': 'component',
                                     'value': u'verification'},
                                 {   'col': 'milestone',
                                     'style': 'milestone',
                                     'value': u'Alpha 3_0'}],
                    'style': 'color-new-odd'},
                {   'cells': [   {   'col': 'ticket',
                                     'style': '',
                                     'value': '(new)'},
                                 {   'col': 'summary',
                                     'style': 'summary',
                                     'value': u'18K ram & regfile integration > simulation with verification model  '},
                                 {   'col': 'component',
                                     'style': 'component',
                                     'value': u'verification'},
                                 {   'col': 'milestone',
                                     'style': 'milestone',
                                     'value': u'Alpha 3_0'}],
                    'style': 'color-new-even'},
                {   'cells': [   {   'col': 'ticket',
                                     'style': '',
                                     'value': '(new)'},
                                 {   'col': 'summary',
                                     'style': 'summary',
                                     'value': u'18K ram & regfile integration > update timming model (.lib)'},
                                 {   'col': 'component',
                                     'style': 'component',
                                     'value': u'verification'},
                                 {   'col': 'milestone',
                                     'style': 'milestone',
                                     'value': u'Alpha 3_0'}],
                    'style': 'color-new-odd'},
                {   'cells': [   {   'col': 'ticket',
                                     'style': '',
                                     'value': '(new)'},
                                 {   'col': 'summary',
                                     'style': 'summary',
                                     'value': u'18K ram & regfile integration > update pluging ztv'},
                                 {   'col': 'component',
                                     'style': 'component',
                                     'value': u'verification'},
                                 {   'col': 'milestone',
                                     'style': 'milestone',
                                     'value': u'Alpha 3_0'}],
                    'style': 'color-new-even'},
                {   'cells': [   {   'col': 'ticket',
                                     'style': '',
                                     'value': '(new)'},
                                 {   'col': 'summary',
                                     'style': 'summary',
                                     'value': u'enable_asynchonous_reset '},
                                 {   'col': 'component',
                                     'style': 'component',
                                     'value': u'timing annalysis'},
                                 {   'col': 'milestone',
                                     'style': 'milestone',
                                     'value': u'Alpha 3_0'}],
                    'style': 'color-new-odd'},
                {   'cells': [   {   'col': 'ticket',
                                     'style': '',
                                     'value': '(new)'},
                                 {   'col': 'summary',
                                     'style': 'summary',
                                     'value': u'asynchonous_path_domain'},
                                 {   'col': 'component',
                                     'style': 'component',
                                     'value': u'timing annalysis'},
                                 {   'col': 'milestone',
                                     'style': 'milestone',
                                     'value': u'Alpha 3_0'}],
                    'style': 'color-new-even'},
                {   'cells': [   {   'col': 'ticket',
                                     'style': '',
                                     'value': '(new)'},
                                 {   'col': 'summary',
                                     'style': 'summary',
                                     'value': u'constrain'},
                                 {   'col': 'component',
                                     'style': 'component',
                                     'value': u'timing annalysis'},
                                 {   'col': 'milestone',
                                     'style': 'milestone',
                                     'value': u'Alpha 3_0'}],
                    'style': 'color-new-odd'},
                {   'cells': [   {   'col': 'ticket',
                                     'style': '',
                                     'value': '(new)'},
                                 {   'col': 'summary',
                                     'style': 'summary',
                                     'value': u'constrain > generated_clock'},
                                 {   'col': 'component',
                                     'style': 'component',
                                     'value': u'timing annalysis'},
                                 {   'col': 'milestone',
                                     'style': 'milestone',
                                     'value': u'Alpha 3_0'}],
                    'style': 'color-new-even'},
                {   'cells': [   {   'col': 'ticket',
                                     'style': '',
                                     'value': '(new)'},
                                 {   'col': 'summary',
                                     'style': 'summary',
                                     'value': u'exception'},
                                 {   'col': 'component',
                                     'style': 'component',
                                     'value': u'timing annalysis'},
                                 {   'col': 'milestone',
                                     'style': 'milestone',
                                     'value': u'Alpha 3_0'}],
                    'style': 'color-new-odd'},
                {   'cells': [   {   'col': 'ticket',
                                     'style': '',
                                     'value': '(new)'},
                                 {   'col': 'summary',
                                     'style': 'summary',
                                     'value': u'exception > subgraph extraction (no -through)'},
                                 {   'col': 'component',
                                     'style': 'component',
                                     'value': u'timing annalysis'},
                                 {   'col': 'milestone',
                                     'style': 'milestone',
                                     'value': u'Alpha 3_0'}],
                    'style': 'color-new-even'},
                {   'cells': [   {   'col': 'ticket',
                                     'style': '',
                                     'value': '(new)'},
                                 {   'col': 'summary',
                                     'style': 'summary',
                                     'value': u'exception > false paths'},
                                 {   'col': 'component',
                                     'style': 'component',
                                     'value': u'timing annalysis'},
                                 {   'col': 'milestone',
                                     'style': 'milestone',
                                     'value': u'Alpha 3_0'}],
                    'style': 'color-new-odd'},
                {   'cells': [   {   'col': 'ticket',
                                     'style': '',
                                     'value': '(new)'},
                                 {   'col': 'summary',
                                     'style': 'summary',
                                     'value': u'exception > false path documentation'},
                                 {   'col': 'component',
                                     'style': 'component',
                                     'value': u'timing annalysis'},
                                 {   'col': 'milestone',
                                     'style': 'milestone',
                                     'value': u'Alpha 3_0'}],
                    'style': 'color-new-even'},
                {   'cells': [   {   'col': 'ticket',
                                     'style': '',
                                     'value': '(new)'},
                                 {   'col': 'summary',
                                     'style': 'summary',
                                     'value': u'exception > multicycle paths'},
                                 {   'col': 'component',
                                     'style': 'component',
                                     'value': u'timing annalysis'},
                                 {   'col': 'milestone',
                                     'style': 'milestone',
                                     'value': u'Alpha 3_0'}],
                    'style': 'color-new-odd'},
                {   'cells': [   {   'col': 'ticket',
                                     'style': '',
                                     'value': '(new)'},
                                 {   'col': 'summary',
                                     'style': 'summary',
                                     'value': u'exception > min/max delay'},
                                 {   'col': 'component',
                                     'style': 'component',
                                     'value': u'timing annalysis'},
                                 {   'col': 'milestone',
                                     'style': 'milestone',
                                     'value': u'Alpha 3_0'}],
                    'style': 'color-new-even'},
                {   'cells': [   {   'col': 'ticket',
                                     'style': '',
                                     'value': '(new)'},
                                 {   'col': 'summary',
                                     'style': 'summary',
                                     'value': u'transfer sdc a.p.i  to top_shell 1'},
                                 {   'col': 'component',
                                     'style': 'component',
                                     'value': u'timing annalysis'},
                                 {   'col': 'milestone',
                                     'style': 'milestone',
                                     'value': u'Alpha 3_0'}],
                    'style': 'color-new-odd'},
                {   'cells': [   {   'col': 'ticket',
                                     'style': '',
                                     'value': '(new)'},
                                 {   'col': 'summary',
                                     'style': 'summary',
                                     'value': u'transfer sdc a.p.i  to top_shell 2'},
                                 {   'col': 'component',
                                     'style': 'component',
                                     'value': u'timing annalysis'},
                                 {   'col': 'milestone',
                                     'style': 'milestone',
                                     'value': u'Alpha 3_0'}],
                    'style': 'color-new-even'},
                {   'cells': [   {   'col': 'ticket',
                                     'style': '',
                                     'value': '(new)'},
                                 {   'col': 'summary',
                                     'style': 'summary',
                                     'value': u'add command'},
                                 {   'col': 'component',
                                     'style': 'component',
                                     'value': u'timing annalysis'},
                                 {   'col': 'milestone',
                                     'style': 'milestone',
                                     'value': u'Alpha 3_0'}],
                    'style': 'color-new-odd'},
                {   'cells': [   {   'col': 'ticket',
                                     'style': '',
                                     'value': '(new)'},
                                 {   'col': 'summary',
                                     'style': 'summary',
                                     'value': u'release'},
                                 {   'col': 'component',
                                     'style': 'component',
                                     'value': u'timing annalysis'},
                                 {   'col': 'milestone',
                                     'style': 'milestone',
                                     'value': u'Alpha 3_0'}],
                    'style': 'color-new-even'},
                {   'cells': [   {   'col': 'ticket',
                                     'style': '',
                                     'value': '(new)'},
                                 {   'col': 'summary',
                                     'style': 'summary',
                                     'value': u'clusterization 1'},
                                 {   'col': 'component',
                                     'style': 'component',
                                     'value': u'Optimization'},
                                 {   'col': 'milestone',
                                     'style': 'milestone',
                                     'value': u'Alpha 3_0'}],
                    'style': 'color-new-odd'},
                {   'cells': [   {   'col': 'ticket',
                                     'style': '',
                                     'value': '(new)'},
                                 {   'col': 'summary',
                                     'style': 'summary',
                                     'value': u'clusterization 2'},
                                 {   'col': 'component',
                                     'style': 'component',
                                     'value': u'Optimization'},
                                 {   'col': 'milestone',
                                     'style': 'milestone',
                                     'value': u'Alpha 3_0'}],
                    'style': 'color-new-even'},
                {   'cells': [   {   'col': 'ticket',
                                     'style': '',
                                     'value': '(new)'},
                                 {   'col': 'summary',
                                     'style': 'summary',
                                     'value': u'integration, quality & regression 1'},
                                 {   'col': 'component',
                                     'style': 'component',
                                     'value': u'release'},
                                 {   'col': 'milestone',
                                     'style': 'milestone',
                                     'value': u'Alpha 3_0'}],
                    'style': 'color-new-odd'},
                {   'cells': [   {   'col': 'ticket',
                                     'style': '',
                                     'value': '(new)'},
                                 {   'col': 'summary',
                                     'style': 'summary',
                                     'value': u'integration, quality & regression 2'},
                                 {   'col': 'component',
                                     'style': 'component',
                                     'value': u'release'},
                                 {   'col': 'milestone',
                                     'style': 'milestone',
                                     'value': u'Alpha 3_0'}],
                    'style': 'color-new-even'},
                {   'cells': [   {   'col': 'ticket',
                                     'style': '',
                                     'value': '(new)'},
                                 {   'col': 'summary',
                                     'style': 'summary',
                                     'value': u'integration, quality & regression 3'},
                                 {   'col': 'component',
                                     'style': 'component',
                                     'value': u'release'},
                                 {   'col': 'milestone',
                                     'style': 'milestone',
                                     'value': u'Alpha 3_0'}],
                    'style': 'color-new-odd'},
                {   'cells': [   {   'col': 'ticket',
                                     'style': '',
                                     'value': '(new)'},
                                 {   'col': 'summary',
                                     'style': 'summary',
                                     'value': u'integration, quality & regression 4'},
                                 {   'col': 'component',
                                     'style': 'component',
                                     'value': u'release'},
                                 {   'col': 'milestone',
                                     'style': 'milestone',
                                     'value': u'Alpha 3_0'}],
                    'style': 'color-new-even'},
                {   'cells': [   {   'col': 'ticket',
                                     'style': '',
                                     'value': '(new)'},
                                 {   'col': 'summary',
                                     'style': 'summary',
                                     'value': u'integration, quality & regression 5'},
                                 {   'col': 'component',
                                     'style': 'component',
                                     'value': u'release'},
                                 {   'col': 'milestone',
                                     'style': 'milestone',
                                     'value': u'Alpha 3_0'}],
                    'style': 'color-new-odd'},
                {   'cells': [   {   'col': 'ticket',
                                     'style': '',
                                     'value': '(new)'},
                                 {   'col': 'summary',
                                     'style': 'summary',
                                     'value': u'integration, quality & regression 6'},
                                 {   'col': 'component',
                                     'style': 'component',
                                     'value': u'release'},
                                 {   'col': 'milestone',
                                     'style': 'milestone',
                                     'value': u'Alpha 3_0'}],
                    'style': 'color-new-even'}],
    'title': 'Preview Import'}
