[   [   (   1,
            u'task',
            1190909220,
            1190909220,
            u'',
            None,
            u'major',
            u'',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'summary1',
            u'',
            u''),
        (   2,
            u'task',
            1190909220,
            1190909220,
            u'',
            None,
            u'major',
            u'',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'summary2',
            u'',
            u'')],
    [   (1, u'mydate', u'01/01/10'),
        (1, u'mydatetime', u'01/01/10'),
        (2, u'mydate', u'12/23/65'),
        (2, u'mydatetime', u'12/23/71')],
    [],
    [],
    []]
