[   [   (   1,
            u'task',
            1190909220000000L,
            1190909220000000L,
            u'',
            None,
            u'major',
            u'me',
            u'me',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'sum1',
            u'',
            u''),
        (   2,
            u'task',
            1190909220000000L,
            1190909220000000L,
            u'',
            None,
            u'major',
            u'',
            u'',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'sum2',
            u'',
            u'')],
    [(1, u'mycustomfield', u''), (2, u'mycustomfield', u'')],
    [],
    [],
    []]