[   [   (   1,
            u'task',
            1190909220000000L,
            1190909220000000L,
            u'',
            None,
            u'major',
            u'newuser1',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'sum1',
            u'',
            u''),
        (   2,
            u'task',
            1190909220000000L,
            1190909220000000L,
            u'',
            None,
            u'major',
            u'newuser2',
            u'testuser',
            u'',
            u'',
            u'',
            u'assigned',
            None,
            u'sum2',
            u'',
            u''),
        (   3,
            u'task',
            1190909220000000L,
            1190909220000000L,
            u'',
            None,
            u'major',
            u'newuser3',
            u'testuser',
            u'',
            u'',
            u'',
            u'accepted',
            None,
            u'sum3',
            u'',
            u'')],
    [   (1, u'mycustomfield', u''),
        (2, u'mycustomfield', u''),
        (3, u'mycustomfield', u'')],
    [],
    [],
    []]