[   [   (   1,
            u'task',
            1190909220,
            1190909220,
            u'mycomp',
            None,
            u'mypriority',
            u'me',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'sum task',
            u'',
            u''),
        (   2,
            u'enhancement',
            1190909220,
            1190909220,
            u'yourcomp',
            None,
            u'yourpriority',
            u'you',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'sum enhancement',
            u'',
            u''),
        (   3,
            u'defect',
            1190909220,
            1190909220,
            u'yourcomp',
            None,
            u'yourpriority',
            u'you',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'sum defect',
            u'',
            u''),
        (   4,
            u'newtype',
            1190909220,
            1190909220,
            u'yourcomp',
            None,
            u'yourpriority',
            u'you',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'sum newtype',
            u'',
            u'')],
    [   (1, u'mycustomfield', u'mycustomfield1'),
        (2, u'mycustomfield', u'customfield2'),
        (3, u'mycustomfield', u'customfield2'),
        (4, u'mycustomfield', u'customfield2')],
    [],
    [   (u'priority', u'yourpriority', u'7'),
        (u'type', u'newtype', u'1'),
        (u'priority', u'mypriority', u'6')],
    [(u'yourcomp', None, None), (u'mycomp', None, None)]]