[   [   (   1245,
            u'defect',
            1191377630,
            1190909220,
            u'yourcomp',
            None,
            u'yourpriority',
            u'you',
            u'anonymous',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'sum2',
            u'',
            u''),
        (   1246,
            u'task',
            1190909220,
            1190909220,
            u'mycomp',
            None,
            u'mypriority',
            u'me',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'sum1',
            u'',
            u'')],
    [   (1245, u'mycustomfield', u'customfield2'),
        (1246, u'mycustomfield', u'mycustomfield1')],
    [   (1245, 1190909220, u'testuser', u'owner', u'somebody', u'you'),
        (   1245,
            1190909220,
            u'testuser',
            u'priority',
            u'major',
            u'yourpriority'),
        (   1245,
            1190909220,
            u'testuser',
            u'component',
            u'component1',
            u'yourcomp'),
        (   1245,
            1190909220,
            u'testuser',
            u'mycustomfield',
            None,
            u'customfield2'),
        (   1245,
            1190909220,
            u'testuser',
            u'comment',
            u'',
            u"''Batch update from file test/simple.csv''")],
    [],
    []]
