[   [   (   1245,
            u'defect',
            1191377630,
            1190909320,
            u'yourcomp',
            None,
            u'yourpriority',
            u'you',
            u'anonymous',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'sum2',
            u'description2',
            u''),
        (   1246,
            u'task',
            1190909220,
            1190909320,
            u'again again mycomp again',
            None,
            u'mypriority',
            u'me again modified',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'sum1',
            u'description1 modified',
            u''),
        (   1247,
            u'task',
            1190909320,
            1190909320,
            u'yourcomp',
            None,
            u'yourpriority',
            u'you',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'newticket',
            u"new description\n[[BR]][[BR]]\n''Batch insert from file test/simple_with_comments_and_description.csv:''\ncomment for a new ticket",
            u'')],
    [   (1245, u'mycustomfield', u'customfield2'),
        (1246, u'mycustomfield', u'mycustomfield1'),
        (1247, u'mycustomfield', u'')],
    [   (1245, 1190909220, u'testuser', u'owner', u'somebody', u'you'),
        (   1245,
            1190909220,
            u'testuser',
            u'priority',
            u'major',
            u'yourpriority'),
        (   1245,
            1190909220,
            u'testuser',
            u'component',
            u'component1',
            u'yourcomp'),
        (   1245,
            1190909220,
            u'testuser',
            u'mycustomfield',
            None,
            u'customfield2'),
        (   1245,
            1190909220,
            u'testuser',
            u'comment',
            u'',
            u"''Batch update from file test/simple.csv''"),
        (   1246,
            1190909320,
            u'testuser',
            u'owner',
            u'me',
            u'me again modified'),
        (   1246,
            1190909320,
            u'testuser',
            u'component',
            u'mycomp',
            u'again again mycomp again'),
        (   1246,
            1190909320,
            u'testuser',
            u'description',
            u'',
            u'description1 modified'),
        (   1246,
            1190909320,
            u'testuser',
            u'comment',
            u'',
            u"''Batch update from file test/simple_with_comments_and_description.csv:'' comment with some modified fields"),
        (1245, 1190909320, u'testuser', u'description', u'', u'description2'),
        (   1245,
            1190909320,
            u'testuser',
            u'comment',
            u'',
            u"''Batch update from file test/simple_with_comments_and_description.csv:'' comment with no field modified")],
    [],
    [(u'again again mycomp again', None, None)]]
