[   [   (   1,
            u'task',
            1190909220,
            1190909220,
            u'',
            None,
            u'major',
            u'',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'test1',
            u'',
            u'')],
    [(1, u'mycustomfield', u'')],
    [],
    [],
    []]