[   [   (   1,
            u'feature',
            1194568349,
            1195073405,
            u'TeamALM',
            u'Medium High',
            u'major',
            u'fredd',
            u'fredd',
            u'',
            u'',
            u'0.03 (Theoden)',
            u'new',
            None,
            u'Using topic maps to visualize, and navigate through, the relationships between items',
            u'Requirements are inter-related:[[BR]]\r\n\r\nThey have dependencies. \r\nThey may have conflicts.\r\nThey may have assumptions, impacts.\r\nThey may parents, children.\r\nThey may affect the same system.\r\nThey may affect the same function.\r\nthey may concern the same geography.\r\n',
            u'Ideas'),
        (   2,
            u'enhancement',
            1194568778,
            1195073352,
            u'TeamALM',
            u'Medium High',
            u'major',
            u'mjh',
            u'fredd',
            u'',
            u'',
            u'0.03 (Theoden)',
            u'new',
            None,
            u'Report of all the ideas, requirements, approaches that have been considered but rejected',
            u'Many ideas are exchanged in projects. Many requirements are expressed. Many approaches are explored. Our assumption is that we need to foster free expression, and that good will come among this.\r\n\r\nBut to develop a piece of software, you need to cut options, and gain clarity and coherence. This implies that among ideas, some would be abandonned. Among a multitude of requirements, some may not be agreed upon by the business, Among conflicting approaches, one would be selected.\r\n\r\nSuch a report would display, on a tabular form, sorted by type, the ideas, requirements, approaches, considered but rejected, and the reason to do so.\r\n\r\nA potential usage could be to onboard a new employee full of ideas that everybody had before them....',
            u'Features'),
        (   3,
            u'benefit',
            1194571440,
            1195176872,
            u'TeamALM',
            u'Medium High',
            u'major',
            u'',
            u'fredd',
            u'',
            u'',
            u'All',
            u'new',
            None,
            u'People "look good" by using it',
            u'The tool provides them with a simple way to handle information and show they are::\r\n* precise\r\n* concise\r\n* clear\r\n* organized\r\n* "on top of things"',
            u''),
        (   4,
            u'benefit',
            1194999257,
            1195002705,
            u'TeamALM',
            u'Medium High',
            u'n/a',
            u'mjh',
            u'fredd',
            u'',
            u'',
            u'',
            u'new',
            u'',
            u'coolness',
            u'not used if not appealing:: nice UI',
            u''),
        (   5,
            u'benefit',
            1194999257,
            1190909220,
            u'TeamALM',
            u'Highest',
            u'n/a',
            u'mjh',
            u'fredd',
            u'',
            u'',
            u'',
            u'new',
            u'',
            u'fun',
            u':: ',
            u''),
        (   6,
            u'benefit',
            1194999257,
            1195002085,
            u'TeamALM',
            u'Highest',
            u'n/a',
            u'mjh',
            u'fredd',
            u'',
            u'',
            u'',
            u'new',
            u'',
            u'human',
            u'not used if cryptic:: no code',
            u''),
        (   7,
            u'benefit',
            1194999257,
            1195066363,
            u'TeamALM',
            u'Medium High',
            u'n/a',
            u'mjh',
            u'fredd',
            u'',
            u'',
            u'',
            u'new',
            u'',
            u'smell of success',
            u'not used if appears flaky:: ',
            u''),
        (   8,
            u'benefit',
            1194999257,
            1195003700,
            u'TeamALM',
            u'Medium High',
            u'n/a',
            u'mjh',
            u'fredd',
            u'',
            u'',
            u'',
            u'new',
            u'',
            u'simple',
            u'not used if complex, needs training:: simple to learn basics, web-based training, on-the-spot training',
            u''),
        (   9,
            u'benefit',
            1194999257,
            1195003753,
            u'TeamALM',
            u'Medium High',
            u'n/a',
            u'mjh',
            u'fredd',
            u'',
            u'',
            u'',
            u'new',
            u'',
            u'efficient',
            u'not used if cumbersome:: ',
            u''),
        (   10,
            u'benefit',
            1194999257,
            1195003726,
            u'TeamALM',
            u'Medium High',
            u'n/a',
            u'mjh',
            u'fredd',
            u'',
            u'',
            u'',
            u'new',
            u'',
            u'automated',
            u'not used if a lot of manual work:: ',
            u''),
        (   11,
            u'benefit',
            1194999257,
            1195003668,
            u'TeamALM',
            u'Medium High',
            u'n/a',
            u'mjh',
            u'fredd',
            u'',
            u'',
            u'',
            u'new',
            u'',
            u'enable control',
            u'not used if leads to moe clutter:: ',
            u''),
        (   12,
            u'benefit',
            1194999257,
            1195066344,
            u'TeamALM',
            u'Medium High',
            u'n/a',
            u'mjh',
            u'fredd',
            u'',
            u'',
            u'',
            u'new',
            u'',
            u'increase probability of project success',
            u':: ',
            u''),
        (   13,
            u'defect',
            1194999830,
            1195001559,
            u'TRAC Import',
            u'Medium High',
            u'n/a',
            u'francoisg',
            u'fredd',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'Clean excel data upload error message',
            u'Python Traceback\r\n\r\nTraceback (most recent call last):\r\n  File "/sw/lib/python2.4/site-packages/trac/web/main.py", line 406, in dispatch_request\r\n    dispatcher.dispatch(req)\r\n  File "/sw/lib/python2.4/site-packages/trac/web/main.py", line 237, in dispatch\r\n    resp = chosen_handler.process_request(req)\r\n  File "build/bdist.darwin-8.10.1-i386/egg/importexport/importer.py", line 151, in process_request\r\n  File "build/bdist.darwin-8.10.1-i386/egg/importexport/importer.py", line 192, in _do_import\r\n  File "build/bdist.darwin-8.10.1-i386/egg/importexport/importer.py", line 458, in _process\r\n  File "build/bdist.darwin-8.10.1-i386/egg/importexport/processors.py", line 156, in process_new_lookups\r\n  File "/sw/lib/python2.4/site-packages/trac/ticket/model.py", line 379, in insert\r\n    (self.type, self.name, self.value))\r\n  File "/sw/lib/python2.4/site-packages/trac/db/util.py", line 50, in execute\r\n    return self.cursor.execute(sql_escape_percent(sql), args)\r\n  File "/sw/lib/python2.4/site-packages/trac/db/sqlite_backend.py", line 56, in execute\r\n    args or [])\r\n  File "/sw/lib/python2.4/site-packages/trac/db/sqlite_backend.py", line 48, in _rollback_on_error\r\n    return function(self, *args, **kwargs)\r\nIntegrityError: columns type, name are not unique\r\n',
            u''),
        (   14,
            u'defect',
            1195000533,
            1195000533,
            u'TRAC Import',
            u'Medium High',
            u'n/a',
            u'francoisg',
            u'fredd',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'Error on Excel Import should give a line  number and even possibly the field that causes the dump',
            u'',
            u''),
        (   15,
            u'defect',
            1195000958,
            1195001396,
            u'TRAC Import',
            u'Highest',
            u'n/a',
            u'francoisg',
            u'fredd',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'Excel import does not read the "type"',
            u'https://office.nexb.us/openalm/report/1\r\n\r\nTickets 4 to 12 are of type "task". They should be of type "benefits" per the excel spreadsheet.',
            u''),
        (   16,
            u'benefit',
            1195001325,
            1195003629,
            u'TeamALM',
            u'Medium High',
            u'n/a',
            u'mjh',
            u'fredd',
            u'',
            u'',
            u'',
            u'new',
            u'',
            u'try a new approach after a failure',
            u':: ',
            u''),
        (   17,
            u'benefit',
            1195001325,
            1195003582,
            u'TeamALM',
            u'Medium High',
            u'n/a',
            u'mjh',
            u'fredd',
            u'',
            u'',
            u'',
            u'new',
            u'',
            u'how will I get people to use it',
            u':: ',
            u''),
        (   18,
            u'benefit',
            1195001325,
            1195003561,
            u'TeamALM',
            u'Medium High',
            u'n/a',
            u'mjh',
            u'fredd',
            u'',
            u'',
            u'',
            u'new',
            u'',
            u'how will I get people to understand the shift',
            u':: ',
            u''),
        (   19,
            u'benefit',
            1195001325,
            1195003524,
            u'TeamALM',
            u'Medium High',
            u'n/a',
            u'mjh',
            u'fredd',
            u'',
            u'',
            u'',
            u'new',
            u'',
            u'how much change will I ask to people',
            u':: Ideally no change to anybody, but transparent change to the whole',
            u''),
        (   20,
            u'benefit',
            1195001325,
            1195003467,
            u'TeamALM',
            u'Medium High',
            u'n/a',
            u'mjh',
            u'fredd',
            u'',
            u'',
            u'',
            u'new',
            u'',
            u'what is it',
            u'not used if not clearly understood/boxed:: ',
            u''),
        (   21,
            u'benefit',
            1195001325,
            1195003434,
            u'TeamALM',
            u'Medium High',
            u'n/a',
            u'mjh',
            u'fredd',
            u'',
            u'',
            u'',
            u'new',
            u'',
            u'will the knowledge in my excel and word be lost',
            u'import .xls and .doc:: ',
            u''),
        (   22,
            u'benefit',
            1195001325,
            1195002676,
            u'TeamALM',
            u'Medium High',
            u'n/a',
            u'mjh',
            u'fredd',
            u'',
            u'',
            u'',
            u'new',
            u'',
            u'zero extra effort',
            u'will not want if it requires more work than usual as perceived:: ',
            u''),
        (   23,
            u'benefit',
            1195001325,
            1195002474,
            u'TeamALM',
            u'Medium High',
            u'n/a',
            u'mjh',
            u'fredd',
            u'',
            u'',
            u'',
            u'new',
            u'',
            u'not be able to blame IT anymore\u2026',
            u':: ',
            u''),
        (   24,
            u'benefit',
            1195001325,
            1195002442,
            u'TeamALM',
            u'Medium High',
            u'n/a',
            u'mjh',
            u'fredd',
            u'',
            u'',
            u'',
            u'new',
            u'',
            u'ability to refine their requirements as the project goes',
            u':: ',
            u''),
        (   25,
            u'benefit',
            1195001325,
            1195002407,
            u'TeamALM',
            u'Medium High',
            u'n/a',
            u'mjh',
            u'fredd',
            u'',
            u'',
            u'',
            u'new',
            u'',
            u'require another install',
            u'no install to light install:: ',
            u''),
        (   26,
            u'benefit',
            1195001325,
            1195002380,
            u'TeamALM',
            u'Medium High',
            u'n/a',
            u'mjh',
            u'fredd',
            u'',
            u'',
            u'',
            u'new',
            u'',
            u'require more training',
            u'self training:: ',
            u''),
        (   27,
            u'benefit',
            1195001325,
            1195002329,
            u'TeamALM',
            u'Medium High',
            u'n/a',
            u'mjh',
            u'fredd',
            u'',
            u'',
            u'',
            u'new',
            u'',
            u'get better result from their interaction with IT on next project (IT behind the curve)',
            u':: ',
            u''),
        (   28,
            u'benefit',
            1195001325,
            1195002301,
            u'TeamALM',
            u'Medium High',
            u'n/a',
            u'mjh',
            u'fredd',
            u'',
            u'',
            u'',
            u'new',
            u'',
            u'ensure that nothing will get missed/forgotten',
            u':: ',
            u''),
        (   29,
            u'benefit',
            1195001325,
            1195002270,
            u'TeamALM',
            u'Medium High',
            u'n/a',
            u'mjh',
            u'fredd',
            u'',
            u'',
            u'',
            u'new',
            u'',
            u'better way to communicate/explain their intent',
            u':: ',
            u''),
        (   30,
            u'defect',
            1195001499,
            1195001499,
            u'TRAC Import',
            u'Highest',
            u'n/a',
            u'francoisg',
            u'fredd',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'Color in the "View Active Tickets" report do not change with severity',
            u'I changed ticket #15 from Severity 3 to Severity 1.\r\nIt is still pinkish on https://office.nexb.us/openalm/report/1',
            u''),
        (   31,
            u'enhancement',
            1195002541,
            1195068366,
            u'TeamALM',
            u'High',
            u'blocker',
            u'mjh',
            u'fredd',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'Users Field needs to be "multi-entry"',
            u'If a benefit is for DV and DL, and I want to finad all the reqs for DV, I should find it in my query',
            u''),
        (   32,
            u'feature',
            1195002623,
            1195002623,
            u'TeamALM',
            u'Medium High',
            u'n/a',
            u'francoisg',
            u'fredd',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'Need to be able to change values of the tickets from the report view',
            u'Do you call this AJAX?\r\nEven if you call this something else, we need it :)',
            u''),
        (   33,
            u'defect',
            1195003343,
            1195003343,
            u'TRAC basic functionality',
            u'Medium High',
            u'n/a',
            u'francoisg',
            u'fredd',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'Cannot find the "Assigned to:" field, when updating a ticket',
            u'',
            u''),
        (   34,
            u'feature',
            1195003784,
            1195003784,
            u'TeamALM',
            u'Medium High',
            u'n/a',
            u'mjh',
            u'fredd',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'Need to be able to manipulate fields in bulks from the report view',
            u'',
            u''),
        (   35,
            u'enhancement',
            1195066638,
            1195606346,
            u'TeamALM',
            u'High',
            u'n/a',
            u'francoisg',
            u'fredd',
            u'mjh, pom',
            u'',
            u'',
            u'new',
            None,
            u'Put everything required to create/update a ticket in one screen',
            u'When updating a ticket, one is compelled to move up and down the screen.\r\n"Everything on one screen" is a good concept to use here.\r\n\r\nThis leads to:\r\n- Ajaxify the "Areas" like ticket properties\r\n- Place the action buttons on the side\r\n\r\n\r\n',
            u''),
        (   36,
            u'enhancement',
            1195066731,
            1195626949,
            u'TeamALM',
            u'Medium High',
            u'minor',
            u'francoisg',
            u'fredd',
            u'mjh, pom',
            u'',
            u'0.01 (Gimli)',
            u'new',
            None,
            u'Enable return from ticket entry to prior screen',
            u'Once a ticket has been created and user is in ticket review screen, provide a button to go back to where they were (before ticket entry)',
            u''),
        (   37,
            u'defect',
            1195066868,
            1195606245,
            u'TeamALM',
            u'High',
            u'major',
            u'francoisg',
            u'fredd',
            u'mjh, pom',
            u'',
            u'',
            u'new',
            None,
            u'Place a legend for the color coding of the report at the top of each report page',
            u'Now I see blue highlighting, pink shading, etc. Completely lost...\r\n\r\nNot a big work, but a big help.',
            u''),
        (   38,
            u'enhancement',
            1195071337,
            1195606239,
            u'TeamALM',
            u'Medium High',
            u'n/a',
            u'francoisg',
            u'fredd',
            u'mjh, pom',
            u'',
            u'',
            u'new',
            None,
            u'Display the "Full description" and "Ticket Properties" of a ticket, when hovering over it on a report',
            u'',
            u''),
        (   39,
            u'enhancement',
            1195071416,
            1195606228,
            u'TeamALM',
            u'Medium High',
            u'n/a',
            u'francoisg',
            u'fredd',
            u'mjh, pom',
            u'',
            u'',
            u'new',
            None,
            u'Enable update of the "Full description" and "Ticket Properties" of a ticket, on the same page, when clicking on it on a report',
            u'',
            u''),
        (   40,
            u'enhancement',
            1195071531,
            1195606186,
            u'TeamALM',
            u'Medium High',
            u'n/a',
            u'francoisg',
            u'fredd',
            u'mjh, pom',
            u'',
            u'0.01 (Gimli)',
            u'new',
            None,
            u'Field "Users" and "CC:" should allow users search by name and id',
            u'',
            u''),
        (   41,
            u'task',
            1195071647,
            1195606153,
            u'TeamALM',
            u'High',
            u'critical',
            u'francoisg',
            u'fredd',
            u'mjh, pom',
            u'',
            u'0.01 (Gimli)',
            u'closed',
            u'fixed',
            u'Install TagsPlugin - Now :) (pleeeeeaaaase)',
            u'',
            u''),
        (   42,
            u'enhancement',
            1195072269,
            1195072379,
            u'TeamALM',
            u'Medium',
            u'n/a',
            u'francoisg',
            u'fredd',
            u'',
            u'',
            u'0.04 (Golum)',
            u'new',
            None,
            u'Enable filtering in reports',
            u'Add a line under heading lines of reports to enable filtering',
            u''),
        (   43,
            u'enhancement',
            1195076585,
            1195076585,
            u'TeamALM',
            u'Medium High',
            u'minor',
            u'francoisg',
            u'fredd',
            u'',
            u'',
            u'0.03 (Theoden)',
            u'new',
            None,
            u'Make the heading of all the reports "active", as in report 1',
            u'',
            u''),
        (   44,
            u'enhancement',
            1195084567,
            1195605170,
            u'TeamALM',
            u'High',
            u'n/a',
            u'francoisg',
            u'fredd',
            u'',
            u'',
            u'0.03 (Theoden)',
            u'new',
            None,
            u'Enable functionality to indicate a ticket is equivalent to another one',
            u'',
            u''),
        (   45,
            u'enhancement',
            1195084961,
            1195084961,
            u'TeamALM',
            u'High',
            u'critical',
            u'francoisg',
            u'fredd',
            u'',
            u'',
            u'0.02 (Frodo)',
            u'new',
            None,
            u'Enable automatic processing, when a ticket is noted as equivalent to another one',
            u'When a ticket is identified as equivalent to another one, a few things should happen:\r\n- this ticket should be archived (and not active anymore)\r\n- this ticket should point to the master, retained, ticket\r\n- the master ticket should point to the archived one for reference\r\n\r\n',
            u''),
        (   46,
            u'task',
            1195150989,
            1196127023,
            u'Trac plugins',
            u'Medium High',
            u'major',
            u'francoisg',
            u'fredd',
            u'',
            u'',
            u'0.01 (Gimli)',
            u'new',
            None,
            u'Install the PlannedMilestonesMacro plugin',
            u'http://trac-hacks.org/wiki/PlannedMilestonesMacro',
            u''),
        (   47,
            u'task',
            1195151237,
            1196127049,
            u'Trac plugins',
            u'Medium High',
            u'major',
            u'francoisg',
            u'fredd',
            u'',
            u'',
            u'0.01 (Gimli)',
            u'new',
            None,
            u'Install the PollMacro plugin',
            u'The purpose of enabling the PollMacro is to provide a tool for team members to vote on the quality or priority of a requirement.',
            u''),
        (   48,
            u'task',
            1195152832,
            1196127098,
            u'Trac plugins',
            u'Medium',
            u'minor',
            u'francoisg',
            u'fredd',
            u'',
            u'',
            u'0.01 (Gimli)',
            u'new',
            None,
            u'Install the TocMacro Plugin',
            u'http://trac-hacks.org/wiki/TocMacro',
            u''),
        (   49,
            u'requirement',
            1195165822,
            1195605783,
            u'TeamALM',
            u'Medium High',
            u'n/a',
            u'mjh',
            u'francois',
            u'',
            u'',
            u'0.01 (Gimli)',
            u'new',
            None,
            u'Minimal rebranding Trac',
            u'\r\nProbably we should rebrand Trac to our branding, either nexB, or an OpenALM/TeamALM branding TBD.\r\n\r\nThis is not about removing the word "trac" everytwere, but to make less proeminent.\r\n\r\nThis would include logo at the top, bottom, and at least a new home page for the wiki.\r\n\r\nAlso there should be a \'Credit\' page for giving credit to Trac.\r\n\r\nMore rebranding planned in #56',
            u''),
        (   50,
            u'task',
            1195165940,
            1195605902,
            u'TeamALM',
            u'Medium High',
            u'n/a',
            u'mjh',
            u'francois',
            u'',
            u'',
            u'Further milestones',
            u'new',
            None,
            u'easy installer of Trac',
            u'Currently setting up Trac can be complex. if we want to have release often, we will need an easy way to install.\r\n\r\nNote taht this is potentially a fair/big amount of work.\r\n\r\nNote that it will be different on different platform. More work...\r\n\r\n',
            u''),
        (   51,
            u'defect',
            1195166029,
            1195626709,
            u'TeamALM',
            u'Medium High',
            u'n/a',
            u'mjh',
            u'francois',
            u'',
            u'',
            u'0.01 (Gimli)',
            u'new',
            None,
            u'Entering tickets with "Highest" severity FAILS !!! and you lose data',
            u'try entering a ticket, with severity "Highest - Data integrity issue". It fails ! and you lose the data if you hit "back".\r\n',
            u''),
        (   52,
            u'task',
            1195166213,
            1196127138,
            u'TRAC basic functionality',
            u'High',
            u'critical',
            u'francoisg',
            u'fredd',
            u'',
            u'',
            u'0.01 (Gimli)',
            u'new',
            None,
            u'Upgrade to Trac 0.11',
            u'',
            u''),
        (   53,
            u'task',
            1195166430,
            1195606193,
            u'TeamALM',
            u'Medium High',
            u'n/a',
            u'mjh',
            u'francois',
            u'',
            u'',
            u'0.01 (Gimli)',
            u'new',
            None,
            u'Improve default values of Trac installation',
            u'Currently, when you install Trac, you get some default values, that are minimalist (following Trac philosophy) but it can be useful to show more functionality. Among them:\r\n * enable email notification on tickets by default\r\n * create a first user, and give him admin rights\r\nplease feel free to add more here...',
            u''),
        (   54,
            u'requirement',
            1195604515,
            1195604638,
            u'TeamALM',
            u'Medium High',
            u'n/a',
            u'mjh',
            u'francois',
            u'',
            u'',
            u'All',
            u'new',
            None,
            u'rework component list',
            u' * RQ configuration (which is the same as "This instance of Trac")\r\n * RQ Requirement items\r\n * RQ Requirement Relations\r\n * RQ Wiki/Item relation\r\nand probably remove the TeamALM generic component.',
            u''),
        (   55,
            u'requirement',
            1195605415,
            1195608013,
            u'TeamALM',
            u'Medium High',
            u'n/a',
            u'mjh',
            u'francois',
            u'',
            u'',
            u'0.01 (Gimli)',
            u'closed',
            u'fixed',
            u'Ticket type by default should be requirement',
            u'',
            u''),
        (   56,
            u'requirement',
            1195605768,
            1195605768,
            u'TeamALM',
            u'Medium High',
            u'n/a',
            u'mjh',
            u'francois',
            u'',
            u'',
            u'All',
            u'new',
            None,
            u'Extensive rebranding of Trac',
            u'TBD - later',
            u''),
        (   57,
            u'requirement',
            1195605978,
            1195605978,
            u'TRAC Import',
            u'Medium High',
            u'n/a',
            u'francoisg',
            u'francois',
            u'',
            u'',
            u'All',
            u'new',
            None,
            u'test if long values in fields work',
            u'',
            u''),
        (   58,
            u'requirement',
            1195606796,
            1195626818,
            u'TeamALM',
            u'Medium High',
            u'n/a',
            u'mjh',
            u'francois',
            u'',
            u'',
            u'0.01 (Gimli)',
            u'new',
            None,
            u'Automatically backtrack between the Wiki and tickets',
            u'When a user creates a link from and item to another one, the backlink needs to be created automatically into the target page:\r\n * wiki page -> ticket\r\n * wiki page -> wiki page\r\n * ticket -> ticket\r\n * ticket -> wiki page\r\n\r\nIt is either documented how to do manually, or a feature that automates the process',
            u''),
        (   59,
            u'requirement',
            1195606796,
            1195606796,
            u'TeamALM',
            u'Medium High',
            u'n/a',
            u'mjh',
            u'pom',
            u'',
            u'',
            u'All',
            u'new',
            None,
            u'We should not have very long description as in Severity',
            u'Instead there should be a way to get an explanantion of code and values there (either by hover, or a link to help page)',
            u''),
        (   60,
            u'requirement',
            1195607216,
            1195627051,
            u'TeamALM',
            u'Medium High',
            u'major',
            u'mjh',
            u'francois',
            u'',
            u'',
            u'0.01 (Gimli)',
            u'new',
            None,
            u'Support a  decision making process',
            u'we need a system that enables you to:\r\n- make decisions about the requyirements captured\r\n- evaluate the validity/value of requirements',
            u''),
        (   61,
            u'requirement',
            1195607559,
            1195608128,
            u'TeamALM',
            u'Medium High',
            u'major',
            u'mjh',
            u'francois',
            u'',
            u'',
            u'0.01 (Gimli)',
            u'new',
            None,
            u'Collaboration actions',
            u'In the action box, there should be a few items leading to further collaboration activities:\r\n * request further details to author\r\n * send/cc: to some people for comments/feedback/updates/details\r\n *  \r\n\r\n\r\n\r\nas configurable to list...',
            u''),
        (   62,
            u'requirement',
            1195607656,
            1195607665,
            u'TeamALM',
            u'Highest',
            u'n/a',
            u'mjh',
            u'francois',
            u'',
            u'',
            u'All',
            u'closed',
            u'invalid',
            u'test - please discard',
            u'',
            u''),
        (   63,
            u'task',
            1195608298,
            1195608298,
            u'TeamALM',
            u'Highest',
            u'n/a',
            u'francoisg',
            u'pom',
            u'',
            u'Release 0.1 (Internal Draft)',
            u'0.01 (Gimli)',
            u'new',
            None,
            u'Put the trac code base under version control....',
            u'',
            u''),
        (   64,
            u'requirement',
            1195614951,
            1195614951,
            u'TeamALM',
            u'Medium High',
            u'n/a',
            u'',
            u'pom',
            u'',
            u'',
            u'All',
            u'new',
            None,
            u'User profile',
            u'to support:\r\n- default field values per user\r\n- memorize the queries\r\n- define the preferences for notifications\r\n- allocation of points/weighting for votes\r\n',
            u''),
        (   65,
            u'requirement',
            1195615022,
            1195615022,
            u'TeamALM',
            u'Highest',
            u'n/a',
            u'',
            u'pom',
            u'',
            u'',
            u'All',
            u'new',
            None,
            u'quicktype like in gmail or google calendar',
            u'To support fast entry of new requirements and text',
            u''),
        (   66,
            u'requirement',
            1195615094,
            1195615094,
            u'TeamALM',
            u'Highest',
            u'n/a',
            u'',
            u'pom',
            u'',
            u'',
            u'All',
            u'new',
            None,
            u'blog this/share this/ RQ this',
            u'Bookmarklet or Firefox extension that would help top very easily create a requirement on this',
            u''),
        (   67,
            u'requirement',
            1195615172,
            1195615172,
            u'TeamALM',
            u'Highest',
            u'n/a',
            u'',
            u'pom',
            u'',
            u'',
            u'All',
            u'new',
            None,
            u'user photos and fullnames as hovers',
            u'to give a face to users',
            u''),
        (   68,
            u'requirement',
            1195615248,
            1195615248,
            u'TeamALM',
            u'Highest',
            u'n/a',
            u'',
            u'pom',
            u'',
            u'',
            u'All',
            u'new',
            None,
            u'be able to get subscription to summary /digest of new stuffs',
            u'get a summary report for a certain topic/subject of interest',
            u''),
        (   69,
            u'specification',
            1195719528,
            1195719528,
            u'TRAC Import',
            u'Medium High',
            u'n/a',
            u'francoisg',
            u'francois',
            u'',
            u'',
            u'0.01 (Gimli)',
            u'new',
            None,
            u"Import plugin should verify that field value aren't too long.",
            u'',
            u''),
        (   70,
            u'defect',
            1196126857,
            1196127072,
            u'Trac plugins',
            u'High',
            u'n/a',
            u'francoisg',
            u'mjh',
            u'',
            u'',
            u'0.01 (Gimli)',
            u'new',
            None,
            u'Tag plugin cannot find tags',
            u'I added Tags to some wiki pages.  When you select Tags from the menubar, it displays the correct tags as links, but when you click for the link you get the error "Link not Found". Specific message is:\r\n\r\n{{{\r\nNot Found\r\nThe requested URL /tags/\'Ideas\' was not found on this server.\r\n\r\nApache/1.3.33 Server at office.nexb.us Port 443\r\n}}}\r\n',
            u''),
        (   71,
            u'defect',
            1190909220,
            1190909220,
            u'',
            u'',
            u'major',
            u'',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'ROI clear',
            u'Not used if unclear benefits:: Estimate benefits for each and for whole',
            u''),
        (   72,
            u'defect',
            1190909220,
            1190909220,
            u'',
            u'',
            u'major',
            u'',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'ROI easy to communicate',
            u'Not used if confusing ROI:: Estimate cost of time wasted and cost of quality',
            u''),
        (   73,
            u'defect',
            1190909220,
            1190909220,
            u'',
            u'',
            u'major',
            u'',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'addresses a compelling pain point',
            u'Not used if no pain point:: Validate/prioritize pain points thru questionnaires and interviews',
            u''),
        (   74,
            u'defect',
            1190909220,
            1190909220,
            u'',
            u'',
            u'major',
            u'',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'can substantiate requirements and link them to business needs',
            u':: ',
            u''),
        (   75,
            u'defect',
            1190909220,
            1190909220,
            u'',
            u'',
            u'major',
            u'',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'involve the whole organization in the gathering and approval of requirements',
            u':: ',
            u''),
        (   76,
            u'defect',
            1190909220,
            1190909220,
            u'',
            u'',
            u'major',
            u'',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'involve the whole organization in the selection of options',
            u':: ',
            u''),
        (   77,
            u'defect',
            1190909220,
            1190909220,
            u'',
            u'',
            u'major',
            u'',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'involve the whole organization in the testing of the solution',
            u':: ',
            u''),
        (   78,
            u'defect',
            1190909220,
            1190909220,
            u'',
            u'',
            u'major',
            u'',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'if it is way better than what they have',
            u':: ',
            u''),
        (   79,
            u'defect',
            1190909220,
            1190909220,
            u'',
            u'',
            u'major',
            u'',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'they agree that what they currently have does not meet their needs',
            u'not used if happy with what they have:: ',
            u''),
        (   80,
            u'defect',
            1190909220,
            1190909220,
            u'',
            u'',
            u'major',
            u'',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'they "look good" by using it - organized',
            u':: ',
            u''),
        (   81,
            u'defect',
            1190909220,
            1190909220,
            u'',
            u'',
            u'major',
            u'',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'they "look good" by using it - precise',
            u':: ',
            u''),
        (   82,
            u'defect',
            1190909220,
            1190909220,
            u'',
            u'',
            u'major',
            u'',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'they "look good" by using it - concise',
            u':: ',
            u''),
        (   83,
            u'defect',
            1190909220,
            1190909220,
            u'',
            u'',
            u'major',
            u'',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'they "look good" by using it - clear',
            u':: ',
            u''),
        (   84,
            u'defect',
            1190909220,
            1190909220,
            u'',
            u'',
            u'major',
            u'',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'they "look good" by using it - on top of things',
            u'not used if easier ways to keep up to date:: ',
            u''),
        (   85,
            u'defect',
            1190909220,
            1190909220,
            u'',
            u'',
            u'major',
            u'',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'price should be ok for a single 3-6 months, $180-360K development project 1',
            u'not more than $30K initially?:: price fits in the expense of such a project (5% = 9K???)',
            u''),
        (   86,
            u'defect',
            1190909220,
            1190909220,
            u'',
            u'',
            u'major',
            u'',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'they can build extensions on top of it, simply, and at low cost',
            u':: API? Documentation? Developers network? ',
            u''),
        (   87,
            u'defect',
            1190909220,
            1190909220,
            u'',
            u'',
            u'major',
            u'',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'price should be ok for a single 3-6 months, $180-360K development project 2',
            u':: Maintenance fees',
            u''),
        (   88,
            u'defect',
            1190909220,
            1190909220,
            u'',
            u'',
            u'major',
            u'',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'price should be ok for a single 3-6 months, $180-360K development project 3',
            u':: Yearly usage fees',
            u''),
        (   89,
            u'defect',
            1190909220,
            1190909220,
            u'',
            u'',
            u'major',
            u'',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'price should be ok for a single 3-6 months, $180-360K development project 4',
            u':: Suggested price (like MySQL)',
            u''),
        (   90,
            u'defect',
            1190909220,
            1190909220,
            u'',
            u'',
            u'major',
            u'',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'justifies their work (they have a system now)',
            u'not used if appears as a way to eliminate ba:: ',
            u''),
        (   91,
            u'defect',
            1190909220,
            1190909220,
            u'',
            u'',
            u'major',
            u'',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'creates some opportunities for cost-cutting',
            u'not used if adds but does not remove anyone:: ',
            u''),
        (   92,
            u'defect',
            1190909220,
            1190909220,
            u'',
            u'',
            u'major',
            u'',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'concrete issues inhouse (failures, delays, under-deliveries, low quality, etc.)',
            u':: Present on the website some pain points and make them into stories',
            u''),
        (   93,
            u'defect',
            1190909220,
            1190909220,
            u'',
            u'',
            u'major',
            u'',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'requirements changes will be logged, tracked, and managed centrally and visible',
            u':: ',
            u''),
        (   94,
            u'defect',
            1190909220,
            1190909220,
            u'',
            u'',
            u'major',
            u'',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'enables easy organized, structured brain dump',
            u':: ',
            u''),
        (   95,
            u'defect',
            1190909220,
            1190909220,
            u'',
            u'',
            u'major',
            u'',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'development manager (dv) is ok with it',
            u':: ',
            u''),
        (   96,
            u'defect',
            1190909220,
            1190909220,
            u'',
            u'',
            u'major',
            u'',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'business analyst (ba) is ok with it',
            u':: ',
            u''),
        (   97,
            u'defect',
            1190909220,
            1190909220,
            u'',
            u'',
            u'major',
            u'',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'PMO mandates it',
            u':: ',
            u''),
        (   98,
            u'defect',
            1190909220,
            1190909220,
            u'',
            u'',
            u'major',
            u'',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'people can experiment it, understand it easily and like it in a snap',
            u':: create a dynamic test environment on a snap',
            u''),
        (   99,
            u'defect',
            1190909220,
            1190909220,
            u'',
            u'',
            u'major',
            u'',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'it saves people time in useless rework and copy-paste',
            u':: saves them from retyping information from document to document',
            u''),
        (   100,
            u'defect',
            1190909220,
            1190909220,
            u'',
            u'',
            u'major',
            u'',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'it enables efficient work with less meetings',
            u':: enables more focused meetings',
            u''),
        (   101,
            u'defect',
            1190909220,
            1190909220,
            u'',
            u'',
            u'major',
            u'',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'ok if it works with my bug tracking system',
            u'not used if incompatible with current RQMS:: ',
            u''),
        (   102,
            u'defect',
            1190909220,
            1190909220,
            u'',
            u'',
            u'major',
            u'',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u"we've always done it that way",
            u':: ',
            u''),
        (   103,
            u'defect',
            1190909220,
            1190909220,
            u'',
            u'',
            u'major',
            u'',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'download it on the web and would try it with their teams',
            u':: ',
            u''),
        (   104,
            u'defect',
            1190909220,
            1190909220,
            u'',
            u'',
            u'major',
            u'',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u"will try it if Analysts say it's good",
            u"will not want to buy it if Analysts say it's crappy:: Seek validation from Analysts",
            u''),
        (   105,
            u'defect',
            1190909220,
            1190909220,
            u'',
            u'',
            u'major',
            u'',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u"will try it if Open-Source Community say it's good",
            u"will not want to buy it if Open-Source Community say it's crappy:: Seek presentation/review in magazines",
            u''),
        (   106,
            u'defect',
            1190909220,
            1190909220,
            u'',
            u'',
            u'major',
            u'',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u"will try it if Magazines say it's good",
            u"will not want to buy it if Magazines say it's crappy:: Seek acceptance/support from Open Source Community",
            u''),
        (   107,
            u'defect',
            1190909220,
            1190909220,
            u'',
            u'',
            u'major',
            u'',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u"will try it if Architects/Infrastructure guys say it's good",
            u"will not want to buy it if Architects/Infrstructure guys say it's crappy:: Seek acceptance/support from Architects through compliance with???",
            u''),
        (   108,
            u'defect',
            1190909220,
            1190909220,
            u'',
            u'',
            u'major',
            u'',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u"may want to buy it if Analysts say it's good",
            u"will not want to buy it if Analysts say it's crappy:: Seek validation from Analysts",
            u''),
        (   109,
            u'defect',
            1190909220,
            1190909220,
            u'',
            u'',
            u'major',
            u'',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u"may want to buy it if Open-Source Community say it's crappy",
            u"will not want to buy it if Open-Source Community say it's crappy:: Seek presentation/review in magazines",
            u''),
        (   110,
            u'defect',
            1190909220,
            1190909220,
            u'',
            u'',
            u'major',
            u'',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u"may want to buy it if Magazines say it's crappy",
            u"will not want to buy it if Magazines say it's crappy:: Seek acceptance/support from Open Source Community",
            u''),
        (   111,
            u'defect',
            1190909220,
            1190909220,
            u'',
            u'',
            u'major',
            u'',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u"may want to buy it if Architects/Infrsatructure guys say it's crappy",
            u"will not want to buy it if Architects/Infrstructure guys say it's crappy:: Seek acceptance/support from Architects through compliance with???",
            u''),
        (   112,
            u'defect',
            1190909220,
            1190909220,
            u'',
            u'',
            u'major',
            u'',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'developing what is needed/the right thing',
            u':: ',
            u''),
        (   113,
            u'defect',
            1190909220,
            1190909220,
            u'',
            u'',
            u'major',
            u'',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'gain control of the process',
            u':: ',
            u''),
        (   114,
            u'defect',
            1190909220,
            1190909220,
            u'',
            u'',
            u'major',
            u'',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'gain visibility on the process/status',
            u':: ',
            u''),
        (   115,
            u'defect',
            1190909220,
            1190909220,
            u'',
            u'',
            u'major',
            u'',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'eliminate the RQ middle man (Business Analyst?)',
            u':: ',
            u''),
        (   116,
            u'defect',
            1190909220,
            1190909220,
            u'',
            u'',
            u'major',
            u'',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'supports the RQ facilitation process',
            u':: ',
            u''),
        (   117,
            u'defect',
            1190909220,
            1190909220,
            u'',
            u'',
            u'major',
            u'',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'uses for personal productivity on their projects',
            u':: ',
            u''),
        (   118,
            u'defect',
            1190909220,
            1190909220,
            u'',
            u'',
            u'major',
            u'',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'system thrives in environments  that are not frozen',
            u':: ',
            u''),
        (   119,
            u'defect',
            1190909220,
            1190909220,
            u'',
            u'',
            u'major',
            u'',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'I can manage my backlog',
            u':: ',
            u''),
        (   120,
            u'defect',
            1190909220,
            1190909220,
            u'',
            u'',
            u'major',
            u'',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'I want my work in progress to be private',
            u':: ',
            u''),
        (   121,
            u'defect',
            1190909220,
            1190909220,
            u'',
            u'',
            u'major',
            u'',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'It helps me onboard team members more easily',
            u':: ',
            u''),
        (   122,
            u'defect',
            1190909220,
            1190909220,
            u'',
            u'',
            u'major',
            u'',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'"I will not buy it because I am using Mercury"',
            u':: Changed ! Find a refutation to this by showing how to work with the tool',
            u''),
        (   123,
            u'defect',
            1190909220,
            1190909220,
            u'',
            u'',
            u'major',
            u'',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'Breaking down in smaller chunks the requirements reduce the WIP',
            u':: ',
            u''),
        (   124,
            u'defect',
            1190909220,
            1190909220,
            u'',
            u'',
            u'major',
            u'',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'Get actionable useful requirements from business side',
            u':: ',
            u''),
        (   125,
            u'defect',
            1190909220,
            1190909220,
            u'',
            u'',
            u'major',
            u'',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'Provides up-to-date information',
            u':: ',
            u''),
        (   126,
            u'defect',
            1190909220,
            1190909220,
            u'',
            u'',
            u'major',
            u'',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'Accelerates the communications and feedback loops',
            u':: ',
            u''),
        (   127,
            u'defect',
            1190909220,
            1190909220,
            u'',
            u'',
            u'major',
            u'',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'Outputs more relevant project deliverables matching the true need',
            u':: ',
            u''),
        (   128,
            u'defect',
            1190909220,
            1190909220,
            u'',
            u'',
            u'major',
            u'',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'Avoids frictions in communications',
            u':: ',
            u''),
        (   129,
            u'defect',
            1190909220,
            1190909220,
            u'',
            u'',
            u'major',
            u'',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'Captures all aspects of requirements, all POVs in one place',
            u':: ',
            u''),
        (   130,
            u'defect',
            1190909220,
            1190909220,
            u'',
            u'',
            u'major',
            u'',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'Provides a global view of requirements and specification (no doing twice the same)',
            u':: ',
            u''),
        (   131,
            u'defect',
            1190909220,
            1190909220,
            u'',
            u'',
            u'major',
            u'',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'Enables developers to code what is really needed',
            u':: ',
            u''),
        (   132,
            u'defect',
            1190909220,
            1190909220,
            u'',
            u'',
            u'major',
            u'',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u"No need to limit down everyone's participation",
            u':: ',
            u''),
        (   133,
            u'defect',
            1190909220,
            1190909220,
            u'',
            u'',
            u'major',
            u'',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'More time to code',
            u':: More description',
            u''),
        (   134,
            u'defect',
            1190909220,
            1190909220,
            u'',
            u'',
            u'major',
            u'',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'No software to deploy to start using',
            u':: web-based? Hosted? Preconfigured? Storable on a usb thumbdrive?',
            u''),
        (   135,
            u'defect',
            1190909220,
            1190909220,
            u'',
            u'',
            u'major',
            u'',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'Identify what is urgent, about to break, broken, opportunities\u2026 help decision',
            u':: ',
            u''),
        (   136,
            u'defect',
            1190909220,
            1190909220,
            u'',
            u'',
            u'major',
            u'',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'Establish a time, place, and way to view requirements synchronously',
            u':: ',
            u''),
        (   137,
            u'defect',
            1190909220,
            1190909220,
            u'',
            u'',
            u'major',
            u'',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'Another tickets',
            u':: ',
            u'')],
    [   (1, u'domain', u''),
        (1, u'stage', u''),
        (1, u'users', u''),
        (2, u'domain', u'Reports, Usage'),
        (2, u'stage', u''),
        (2, u'users', u''),
        (   3,
            u'benefits',
            u'Business Analyst, Developer, Development Lead, QA Lead, QA, Project Manager'),
        (3, u'domain', u''),
        (3, u'stage', u''),
        (3, u'users', u''),
        (4, u'domain', u''),
        (4, u'stage', u''),
        (4, u'users', u''),
        (5, u'domain', u''),
        (5, u'stage', u''),
        (5, u'users', u'DV'),
        (6, u'domain', u''),
        (6, u'stage', u''),
        (6, u'users', u'PM'),
        (7, u'domain', u''),
        (7, u'stage', u''),
        (7, u'users', u'PM'),
        (8, u'domain', u''),
        (8, u'stage', u''),
        (8, u'users', u'PM'),
        (9, u'domain', u''),
        (9, u'stage', u''),
        (9, u'users', u'PM'),
        (10, u'domain', u''),
        (10, u'stage', u''),
        (10, u'users', u'PM'),
        (11, u'domain', u''),
        (11, u'stage', u''),
        (11, u'users', u'PM'),
        (12, u'domain', u''),
        (12, u'stage', u''),
        (12, u'users', u'PM'),
        (13, u'domain', u''),
        (13, u'stage', u''),
        (13, u'users', u''),
        (14, u'domain', u''),
        (14, u'stage', u''),
        (14, u'users', u''),
        (15, u'domain', u''),
        (15, u'stage', u''),
        (15, u'users', u''),
        (16, u'domain', u''),
        (16, u'stage', u''),
        (16, u'users', u'PM'),
        (17, u'domain', u''),
        (17, u'stage', u''),
        (17, u'users', u'PM'),
        (18, u'domain', u''),
        (18, u'stage', u''),
        (18, u'users', u'PM'),
        (19, u'domain', u''),
        (19, u'stage', u''),
        (19, u'users', u'PM'),
        (20, u'domain', u''),
        (20, u'stage', u''),
        (20, u'users', u'PM'),
        (21, u'domain', u''),
        (21, u'stage', u''),
        (21, u'users', u'PM'),
        (22, u'domain', u''),
        (22, u'stage', u''),
        (22, u'users', u'DL,DV,QL,QA,PM'),
        (23, u'domain', u''),
        (23, u'stage', u''),
        (23, u'users', u'DL,DV,QL,QA'),
        (24, u'domain', u''),
        (24, u'stage', u''),
        (24, u'users', u''),
        (25, u'domain', u''),
        (25, u'stage', u''),
        (25, u'users', u''),
        (26, u'domain', u''),
        (26, u'stage', u''),
        (26, u'users', u''),
        (27, u'domain', u''),
        (27, u'stage', u''),
        (27, u'users', u''),
        (28, u'domain', u''),
        (28, u'stage', u''),
        (28, u'users', u''),
        (29, u'domain', u''),
        (29, u'stage', u''),
        (29, u'users', u''),
        (30, u'domain', u''),
        (30, u'stage', u''),
        (30, u'users', u''),
        (31, u'domain', u'UI'),
        (31, u'stage', u''),
        (31, u'users', u''),
        (32, u'domain', u''),
        (32, u'stage', u''),
        (32, u'users', u''),
        (33, u'domain', u''),
        (33, u'stage', u''),
        (33, u'users', u''),
        (34, u'domain', u''),
        (34, u'stage', u''),
        (34, u'users', u''),
        (35, u'domain', u'UI'),
        (35, u'stage', u''),
        (35, u'users', u'All'),
        (36, u'domain', u'UI'),
        (36, u'stage', u''),
        (36, u'users', u''),
        (37, u'domain', u'UI'),
        (37, u'stage', u''),
        (37, u'users', u''),
        (38, u'domain', u'UI'),
        (38, u'stage', u''),
        (38, u'users', u''),
        (39, u'domain', u'UI'),
        (39, u'stage', u''),
        (39, u'users', u''),
        (40, u'domain', u'UI'),
        (40, u'stage', u''),
        (40, u'users', u''),
        (41, u'domain', u'UI'),
        (41, u'stage', u''),
        (41, u'users', u''),
        (42, u'domain', u'UI'),
        (42, u'stage', u''),
        (42, u'users', u''),
        (43, u'domain', u''),
        (43, u'stage', u''),
        (43, u'users', u''),
        (44, u'domain', u'UI'),
        (44, u'stage', u''),
        (44, u'users', u''),
        (45, u'domain', u'UI'),
        (45, u'stage', u''),
        (45, u'users', u''),
        (46, u'domain', u'UI'),
        (46, u'stage', u''),
        (46, u'users', u''),
        (47, u'domain', u'UI'),
        (47, u'stage', u''),
        (47, u'users', u''),
        (48, u'domain', u'UI'),
        (48, u'stage', u''),
        (48, u'users', u''),
        (49, u'domain', u''),
        (49, u'stage', u''),
        (49, u'users', u''),
        (50, u'domain', u''),
        (50, u'stage', u''),
        (50, u'users', u''),
        (51, u'domain', u''),
        (51, u'stage', u''),
        (51, u'users', u''),
        (52, u'domain', u'Infrastructure'),
        (52, u'stage', u''),
        (52, u'users', u''),
        (53, u'domain', u''),
        (53, u'stage', u''),
        (53, u'users', u''),
        (54, u'domain', u''),
        (54, u'stage', u''),
        (54, u'users', u''),
        (55, u'domain', u''),
        (55, u'stage', u''),
        (55, u'users', u''),
        (56, u'domain', u''),
        (56, u'stage', u''),
        (56, u'users', u''),
        (57, u'domain', u''),
        (57, u'stage', u''),
        (57, u'users', u''),
        (58, u'domain', u''),
        (58, u'stage', u''),
        (58, u'users', u''),
        (59, u'domain', u''),
        (59, u'stage', u''),
        (59, u'users', u''),
        (60, u'domain', u''),
        (60, u'stage', u''),
        (60, u'users', u''),
        (61, u'domain', u''),
        (61, u'stage', u''),
        (61, u'users', u''),
        (62, u'domain', u''),
        (62, u'stage', u''),
        (62, u'users', u''),
        (63, u'domain', u''),
        (63, u'stage', u''),
        (63, u'users', u''),
        (64, u'domain', u''),
        (64, u'stage', u''),
        (64, u'users', u''),
        (65, u'domain', u''),
        (65, u'stage', u''),
        (65, u'users', u''),
        (66, u'domain', u''),
        (66, u'stage', u''),
        (66, u'users', u''),
        (67, u'domain', u''),
        (67, u'stage', u''),
        (67, u'users', u''),
        (68, u'domain', u''),
        (68, u'stage', u''),
        (68, u'users', u''),
        (69, u'domain', u''),
        (69, u'stage', u''),
        (69, u'users', u''),
        (70, u'domain', u''),
        (70, u'stage', u''),
        (70, u'users', u''),
        (71, u'domain', u''),
        (71, u'stage', u''),
        (71, u'users', u'DL,DV,QL,QA,PM'),
        (72, u'domain', u''),
        (72, u'stage', u''),
        (72, u'users', u'DL,DV,QL,QA,PM'),
        (73, u'domain', u''),
        (73, u'stage', u''),
        (73, u'users', u'DL,DV,PM'),
        (74, u'domain', u''),
        (74, u'stage', u''),
        (74, u'users', u''),
        (75, u'domain', u''),
        (75, u'stage', u''),
        (75, u'users', u''),
        (76, u'domain', u''),
        (76, u'stage', u''),
        (76, u'users', u'DL'),
        (77, u'domain', u''),
        (77, u'stage', u''),
        (77, u'users', u'DL'),
        (78, u'domain', u''),
        (78, u'stage', u''),
        (78, u'users', u'DL'),
        (79, u'domain', u''),
        (79, u'stage', u''),
        (79, u'users', u'DL'),
        (80, u'domain', u''),
        (80, u'stage', u''),
        (80, u'users', u'DL,DV,QL,QA,PM'),
        (81, u'domain', u''),
        (81, u'stage', u''),
        (81, u'users', u'DL,DV,QL,QA,PM'),
        (82, u'domain', u''),
        (82, u'stage', u''),
        (82, u'users', u'DL,DV,QL,QA,PM'),
        (83, u'domain', u''),
        (83, u'stage', u''),
        (83, u'users', u'DL,DV,QL,QA,PM'),
        (84, u'domain', u''),
        (84, u'stage', u''),
        (84, u'users', u'DL,DV,QL,QA,PM'),
        (85, u'domain', u''),
        (85, u'stage', u''),
        (85, u'users', u'Buyer'),
        (86, u'domain', u''),
        (86, u'stage', u''),
        (86, u'users', u'DL'),
        (87, u'domain', u''),
        (87, u'stage', u''),
        (87, u'users', u'Buyer'),
        (88, u'domain', u''),
        (88, u'stage', u''),
        (88, u'users', u'Buyer'),
        (89, u'domain', u''),
        (89, u'stage', u''),
        (89, u'users', u'Buyer'),
        (90, u'domain', u''),
        (90, u'stage', u''),
        (90, u'users', u''),
        (91, u'domain', u''),
        (91, u'stage', u''),
        (91, u'users', u'Buyer'),
        (92, u'domain', u''),
        (92, u'stage', u''),
        (92, u'users', u'Buyer'),
        (93, u'domain', u''),
        (93, u'stage', u''),
        (93, u'users', u'DV'),
        (94, u'domain', u''),
        (94, u'stage', u''),
        (94, u'users', u'DL,DV,QL,QA,PM'),
        (95, u'domain', u''),
        (95, u'stage', u''),
        (95, u'users', u'DV'),
        (96, u'domain', u''),
        (96, u'stage', u''),
        (96, u'users', u'DV'),
        (97, u'domain', u''),
        (97, u'stage', u''),
        (97, u'users', u'DV'),
        (98, u'domain', u''),
        (98, u'stage', u''),
        (98, u'users', u'DL,DV,QL,QA,PM'),
        (99, u'domain', u''),
        (99, u'stage', u''),
        (99, u'users', u'DL,DV,QL,QA,PM'),
        (100, u'domain', u''),
        (100, u'stage', u''),
        (100, u'users', u'DL,DV,QL,QA,PM'),
        (101, u'domain', u''),
        (101, u'stage', u''),
        (101, u'users', u'DV'),
        (102, u'domain', u''),
        (102, u'stage', u''),
        (102, u'users', u''),
        (103, u'domain', u''),
        (103, u'stage', u''),
        (103, u'users', u'DL'),
        (104, u'domain', u''),
        (104, u'stage', u''),
        (104, u'users', u'DL'),
        (105, u'domain', u''),
        (105, u'stage', u''),
        (105, u'users', u'DV'),
        (106, u'domain', u''),
        (106, u'stage', u''),
        (106, u'users', u'DV'),
        (107, u'domain', u''),
        (107, u'stage', u''),
        (107, u'users', u'DL,DV'),
        (108, u'domain', u''),
        (108, u'stage', u''),
        (108, u'users', u'Buyer'),
        (109, u'domain', u''),
        (109, u'stage', u''),
        (109, u'users', u'Buyer'),
        (110, u'domain', u''),
        (110, u'stage', u''),
        (110, u'users', u'Buyer'),
        (111, u'domain', u''),
        (111, u'stage', u''),
        (111, u'users', u'Buyer'),
        (112, u'domain', u''),
        (112, u'stage', u''),
        (112, u'users', u'DV'),
        (113, u'domain', u''),
        (113, u'stage', u''),
        (113, u'users', u'DL,DV,QL,QA,PM'),
        (114, u'domain', u''),
        (114, u'stage', u''),
        (114, u'users', u'DL,DV,QL,QA,PM'),
        (115, u'domain', u''),
        (115, u'stage', u''),
        (115, u'users', u'DV'),
        (116, u'domain', u''),
        (116, u'stage', u''),
        (116, u'users', u''),
        (117, u'domain', u''),
        (117, u'stage', u''),
        (117, u'users', u''),
        (118, u'domain', u''),
        (118, u'stage', u''),
        (118, u'users', u'DL,DV,QL,QA,PM'),
        (119, u'domain', u''),
        (119, u'stage', u''),
        (119, u'users', u'DL,DV,QL,QA,PM'),
        (120, u'domain', u''),
        (120, u'stage', u''),
        (120, u'users', u'DL,DV,QL,QA,PM'),
        (121, u'domain', u''),
        (121, u'stage', u''),
        (121, u'users', u'DL,QL,PM'),
        (122, u'domain', u''),
        (122, u'stage', u''),
        (122, u'users', u'QL'),
        (123, u'domain', u''),
        (123, u'stage', u''),
        (123, u'users', u'DL,DV,QL,QA,PM'),
        (124, u'domain', u''),
        (124, u'stage', u''),
        (124, u'users', u'DL,DV,QL,QA'),
        (125, u'domain', u''),
        (125, u'stage', u''),
        (125, u'users', u'DL,DV,QL,QA,PM'),
        (126, u'domain', u''),
        (126, u'stage', u''),
        (126, u'users', u'DL,DV,QL,QA,PM'),
        (127, u'domain', u''),
        (127, u'stage', u''),
        (127, u'users', u'PM'),
        (128, u'domain', u''),
        (128, u'stage', u''),
        (128, u'users', u'DL,DV,QL,QA,PM'),
        (129, u'domain', u''),
        (129, u'stage', u''),
        (129, u'users', u'DL,DV,QL,QA,PM'),
        (130, u'domain', u''),
        (130, u'stage', u''),
        (130, u'users', u'DL,DV,QL,QA,PM'),
        (131, u'domain', u''),
        (131, u'stage', u''),
        (131, u'users', u'DL,DV'),
        (132, u'domain', u''),
        (132, u'stage', u''),
        (132, u'users', u'DL,DV,QL,QA,PM'),
        (133, u'domain', u''),
        (133, u'stage', u''),
        (133, u'users', u'DL'),
        (134, u'domain', u''),
        (134, u'stage', u''),
        (134, u'users', u'DL,DV,QL,QA,PM,Buyer'),
        (135, u'domain', u''),
        (135, u'stage', u''),
        (135, u'users', u''),
        (136, u'domain', u''),
        (136, u'stage', u''),
        (136, u'users', u''),
        (137, u'domain', u''),
        (137, u'stage', u''),
        (137, u'users', u'')],
    [   (   3,
            1194572983,
            u'fredd',
            u'benefits',
            u'',
            u'Business Analyst, Developer, Development Lead, QA Lead, QA, Project Manager'),
        (3, 1194572983, u'fredd', u'comment', u'1', u''),
        (4, 1195001046, u'fredd', u'owner', u'', u'francoisg'),
        (4, 1195001046, u'fredd', u'type', u'task', u'benefit'),
        (4, 1195001046, u'fredd', u'component', u'', u'TRAC Import'),
        (4, 1195001046, u'fredd', u'comment', u'1', u''),
        (15, 1195001396, u'fredd', u'severity', u'3', u'1'),
        (15, 1195001396, u'fredd', u'comment', u'1', u''),
        (   13,
            1195001559,
            u'fredd',
            u'summary',
            u'Clean excel data upload',
            u'Clean excel data upload error message'),
        (13, 1195001559, u'fredd', u'comment', u'1', u''),
        (5, 1195002053, u'fredd', u'owner', u'', u'mjh'),
        (5, 1195002053, u'fredd', u'component', u'', u'TeamALM'),
        (5, 1195002053, u'fredd', u'severity', u'3', u'1'),
        (5, 1195002053, u'fredd', u'comment', u'1', u''),
        (6, 1195002085, u'fredd', u'owner', u'', u'mjh'),
        (6, 1195002085, u'fredd', u'type', u'task', u'benefit'),
        (6, 1195002085, u'fredd', u'component', u'', u'TeamALM'),
        (6, 1195002085, u'fredd', u'severity', u'3', u'1'),
        (6, 1195002085, u'fredd', u'comment', u'1', u''),
        (29, 1195002270, u'fredd', u'type', u'task', u'benefit'),
        (29, 1195002270, u'fredd', u'comment', u'1', u''),
        (28, 1195002301, u'fredd', u'type', u'task', u'benefit'),
        (28, 1195002301, u'fredd', u'comment', u'1', u''),
        (27, 1195002329, u'fredd', u'type', u'task', u'benefit'),
        (27, 1195002329, u'fredd', u'comment', u'1', u''),
        (26, 1195002380, u'fredd', u'type', u'task', u'benefit'),
        (26, 1195002380, u'fredd', u'comment', u'1', u''),
        (25, 1195002407, u'fredd', u'type', u'task', u'benefit'),
        (25, 1195002407, u'fredd', u'comment', u'1', u''),
        (24, 1195002442, u'fredd', u'type', u'task', u'benefit'),
        (24, 1195002442, u'fredd', u'comment', u'1', u''),
        (23, 1195002474, u'fredd', u'type', u'task', u'benefit'),
        (23, 1195002474, u'fredd', u'comment', u'1', u''),
        (22, 1195002676, u'fredd', u'type', u'task', u'benefit'),
        (22, 1195002676, u'fredd', u'comment', u'1', u''),
        (4, 1195002705, u'fredd', u'owner', u'francoisg', u'mjh'),
        (4, 1195002705, u'fredd', u'component', u'TRAC Import', u'TeamALM'),
        (4, 1195002705, u'fredd', u'comment', u'2', u''),
        (1, 1195002985, u'fredd', u'domain', None, u''),
        (1, 1195002985, u'fredd', u'severity', u'', u'1'),
        (1, 1195002985, u'fredd', u'component', u'', u'TeamALM'),
        (1, 1195002985, u'fredd', u'priority', u'', u'major'),
        (1, 1195002985, u'fredd', u'owner', u'', u'mjh'),
        (1, 1195002985, u'fredd', u'stage', None, u''),
        (1, 1195002985, u'fredd', u'users', None, u''),
        (1, 1195002985, u'fredd', u'comment', u'1', u''),
        (1, 1195003004, u'fredd', u'type', u'defect', u'feature'),
        (1, 1195003004, u'fredd', u'severity', u'1', u'3'),
        (1, 1195003004, u'fredd', u'comment', u'2', u''),
        (5, 1195003392, u'fredd', u'type', u'task', u'benefit'),
        (5, 1195003392, u'fredd', u'comment', u'2', u''),
        (21, 1195003434, u'fredd', u'type', u'task', u'benefit'),
        (21, 1195003434, u'fredd', u'comment', u'1', u''),
        (20, 1195003467, u'fredd', u'type', u'task', u'benefit'),
        (20, 1195003467, u'fredd', u'comment', u'1', u''),
        (7, 1195003490, u'fredd', u'owner', u'', u'francoisg'),
        (7, 1195003490, u'fredd', u'type', u'task', u'benefit'),
        (7, 1195003490, u'fredd', u'component', u'', u'TRAC Import'),
        (7, 1195003490, u'fredd', u'comment', u'1', u''),
        (19, 1195003524, u'fredd', u'type', u'task', u'benefit'),
        (19, 1195003524, u'fredd', u'comment', u'1', u''),
        (18, 1195003561, u'fredd', u'type', u'task', u'benefit'),
        (18, 1195003561, u'fredd', u'comment', u'1', u''),
        (17, 1195003582, u'fredd', u'type', u'task', u'benefit'),
        (17, 1195003582, u'fredd', u'comment', u'1', u''),
        (12, 1195003602, u'fredd', u'owner', u'', u'francoisg'),
        (12, 1195003602, u'fredd', u'type', u'task', u'benefit'),
        (12, 1195003602, u'fredd', u'component', u'', u'TRAC Import'),
        (12, 1195003602, u'fredd', u'comment', u'1', u''),
        (16, 1195003629, u'fredd', u'type', u'task', u'benefit'),
        (16, 1195003629, u'fredd', u'comment', u'1', u''),
        (11, 1195003668, u'fredd', u'owner', u'', u'mjh'),
        (11, 1195003668, u'fredd', u'type', u'task', u'benefit'),
        (11, 1195003668, u'fredd', u'component', u'', u'TeamALM'),
        (11, 1195003668, u'fredd', u'comment', u'1', u''),
        (8, 1195003700, u'fredd', u'owner', u'', u'mjh'),
        (8, 1195003700, u'fredd', u'type', u'task', u'benefit'),
        (8, 1195003700, u'fredd', u'component', u'', u'TeamALM'),
        (8, 1195003700, u'fredd', u'comment', u'1', u''),
        (10, 1195003726, u'fredd', u'owner', u'', u'mjh'),
        (10, 1195003726, u'fredd', u'type', u'task', u'benefit'),
        (10, 1195003726, u'fredd', u'component', u'', u'TeamALM'),
        (10, 1195003726, u'fredd', u'comment', u'1', u''),
        (9, 1195003753, u'fredd', u'owner', u'', u'mjh'),
        (9, 1195003753, u'fredd', u'type', u'task', u'benefit'),
        (9, 1195003753, u'fredd', u'component', u'', u'TeamALM'),
        (9, 1195003753, u'fredd', u'comment', u'1', u''),
        (12, 1195066344, u'fredd', u'owner', u'francoisg', u'mjh'),
        (12, 1195066344, u'fredd', u'component', u'TRAC Import', u'TeamALM'),
        (12, 1195066344, u'fredd', u'comment', u'2', u''),
        (7, 1195066363, u'fredd', u'owner', u'francoisg', u'mjh'),
        (7, 1195066363, u'fredd', u'component', u'TRAC Import', u'TeamALM'),
        (7, 1195066363, u'fredd', u'comment', u'2', u''),
        (36, 1195066750, u'fredd', u'priority', u'n/a', u'minor'),
        (36, 1195066750, u'fredd', u'severity', u'2', u'3'),
        (36, 1195066750, u'fredd', u'comment', u'1', u''),
        (31, 1195068354, u'fredd', u'priority', u'n/a', u'blocker'),
        (31, 1195068354, u'fredd', u'type', u'feature', u'enhancement'),
        (31, 1195068354, u'fredd', u'severity', u'3', u'2'),
        (31, 1195068354, u'fredd', u'comment', u'1', u''),
        (31, 1195068366, u'fredd', u'domain', u'', u'UI'),
        (31, 1195068366, u'fredd', u'comment', u'2', u''),
        (38, 1195071347, u'fredd', u'domain', u'', u'UI'),
        (38, 1195071347, u'fredd', u'comment', u'1', u''),
        (39, 1195071429, u'fredd', u'keywords', u'UI', u''),
        (39, 1195071429, u'fredd', u'domain', u'', u'UI'),
        (39, 1195071429, u'fredd', u'comment', u'1', u''),
        (39, 1195071469, u'fredd', u'type', u'defect', u'enhancement'),
        (39, 1195071469, u'fredd', u'comment', u'2', u''),
        (41, 1195071668, u'fredd', u'priority', u'n/a', u'critical'),
        (41, 1195071668, u'fredd', u'type', u'defect', u'task'),
        (41, 1195071668, u'fredd', u'comment', u'1', u''),
        (42, 1195072334, u'fredd', u'domain', u'', u'UI'),
        (   42,
            1195072334,
            u'fredd',
            u'severity',
            u'Low - General questions. Minor inconsistencies that cause hesitation or small aesthetic issues.',
            u'Medium - Limited problem (no data lost or system failure). Does not hinder operation and can be avoided. But causes users confusion or irritation.'),
        (42, 1195072334, u'fredd', u'cc', u'', u'francoisg'),
        (   42,
            1195072334,
            u'fredd',
            u'summary',
            u'Add a line under heading lines of reports to',
            u'Enable filtering in reports'),
        (   42,
            1195072334,
            u'fredd',
            u'milestone',
            u'Further releases',
            u'Release 0.04 (Golum)'),
        (   42,
            1195072334,
            u'fredd',
            u'description',
            u'',
            u'Add a line under heading lines of reports to enable filtering'),
        (42, 1195072334, u'fredd', u'comment', u'1', u''),
        (42, 1195072379, u'fredd', u'cc', u'francoisg', u''),
        (42, 1195072379, u'fredd', u'owner', u'mjh', u'francoisg'),
        (42, 1195072379, u'fredd', u'type', u'defect', u'enhancement'),
        (42, 1195072379, u'fredd', u'comment', u'2', u''),
        (2, 1195073306, u'fredd', u'owner', u'', u'francoisg'),
        (2, 1195073306, u'fredd', u'domain', None, u''),
        (2, 1195073306, u'fredd', u'component', u'', u'TRAC Import'),
        (2, 1195073306, u'fredd', u'users', None, u''),
        (2, 1195073306, u'fredd', u'stage', None, u''),
        (2, 1195073306, u'fredd', u'comment', u'1', u''),
        (2, 1195073319, u'fredd', u'domain', u'', u'Reports, Usage'),
        (2, 1195073319, u'fredd', u'comment', u'2', u''),
        (   2,
            1195073336,
            u'fredd',
            u'milestone',
            u'',
            u'Release 0.03 (Theoden)'),
        (2, 1195073336, u'fredd', u'comment', u'3', u''),
        (2, 1195073344, u'fredd', u'type', u'defect', u'enhancement'),
        (2, 1195073344, u'fredd', u'comment', u'4', u''),
        (2, 1195073352, u'fredd', u'owner', u'francoisg', u'mjh'),
        (2, 1195073352, u'fredd', u'component', u'TRAC Import', u'TeamALM'),
        (2, 1195073352, u'fredd', u'comment', u'5', u''),
        (1, 1195073405, u'fredd', u'owner', u'mjh', u'fredd'),
        (   1,
            1195073405,
            u'fredd',
            u'milestone',
            u'',
            u'Release 0.03 (Theoden)'),
        (1, 1195073405, u'fredd', u'comment', u'3', u''),
        (   36,
            1195083705,
            u'fredd',
            u'milestone',
            u'',
            u'Release 0.01 (Gimli)'),
        (36, 1195083705, u'fredd', u'comment', u'2', u''),
        (41, 1195085408, u'fredd', u'status', u'new', u'closed'),
        (41, 1195085408, u'fredd', u'resolution', u'', u'fixed'),
        (41, 1195085408, u'fredd', u'comment', u'2', u''),
        (   41,
            1195085579,
            u'fredd',
            u'milestone',
            u'',
            u'Release 0.01 (Gimli)'),
        (41, 1195085579, u'fredd', u'comment', u'3', u''),
        (   40,
            1195085666,
            u'fredd',
            u'milestone',
            u'',
            u'Release 0.01 (Gimli)'),
        (40, 1195085666, u'fredd', u'comment', u'1', u''),
        (46, 1195151138, u'fredd', u'priority', u'n/a', u'major'),
        (46, 1195151138, u'fredd', u'type', u'defect', u'task'),
        (46, 1195151138, u'fredd', u'comment', u'1', u''),
        (48, 1195152846, u'fredd', u'type', u'enhancement', u'task'),
        (48, 1195152846, u'fredd', u'comment', u'1', u''),
        (   49,
            1195165842,
            u'francois',
            u'summary',
            u'Rebrand / remorph Trac',
            u'Rebrand Trac'),
        (49, 1195165842, u'francois', u'comment', u'1', u''),
        (   51,
            1195166096,
            u'francois',
            u'description',
            u'',
            u'try entering a ticket, with severity "Highest - Data integrity issue". It fails ! and you loose the data if you hit "back".\r\n'),
        (51, 1195166096, u'francois', u'comment', u'1', u''),
        (53, 1195166439, u'francois', u'type', u'defect', u'task'),
        (53, 1195166439, u'francois', u'comment', u'1', u''),
        (   51,
            1195166868,
            u'francois',
            u'comment',
            u'2',
            u"let's not try to understand how *why* it happens, but at least fix it in this instance of Trac."),
        (3, 1195176872, u'fredd', u'milestone', u'', u'All'),
        (3, 1195176872, u'fredd', u'comment', u'2', u''),
        (   54,
            1195604638,
            u'francois',
            u'description',
            u' * This instance of Trac only\r\n * RQ Requirement items\r\n * RQ Requirement Relations\r\n * RQ Wiki/Item relation\r\nand probably remove the TeamALM generic component.',
            u' * RQ configuration (which is the same as "This instance of Trac")\r\n * RQ Requirement items\r\n * RQ Requirement Relations\r\n * RQ Wiki/Item relation\r\nand probably remove the TeamALM generic component.'),
        (54, 1195604638, u'francois', u'comment', u'1', u''),
        (   36,
            1195604920,
            u'francois',
            u'comment',
            u'3',
            u'Probably OK in 0.11. On hold until #52 is done.'),
        (   40,
            1195605056,
            u'francois',
            u'comment',
            u'2',
            u'drop-down is enough. This is a default configuration to enable + some user management to do (i.e. add all the users to the DB).'),
        (   44,
            1195605146,
            u'francois',
            u'comment',
            u'1',
            u'this: http://simple.wikipedia.org/wiki/Wikipedia:Merging_and_moving_pages is an interesting document to read on this subject.'),
        (   44,
            1195605170,
            u'francois',
            u'milestone',
            u'0.01 (Gimli)',
            u'0.03 (Theoden)'),
        (44, 1195605170, u'francois', u'comment', u'2', u''),
        (   36,
            1195605312,
            u'francois',
            u'comment',
            u'4',
            u"also, there's an alternative: open in new tab. But maybe there should be a nice cute button on each line of the report to open tickets in a new tab."),
        (   36,
            1195605330,
            u'francois',
            u'comment',
            u'5',
            u'Bu this may be browser-specific :('),
        (49, 1195605372, u'francois', u'type', u'defect', u'requirement'),
        (49, 1195605372, u'francois', u'comment', u'2', u''),
        (55, 1195605419, u'francois', u'status', u'new', u'closed'),
        (55, 1195605419, u'francois', u'resolution', u'', u'fixed'),
        (55, 1195605419, u'francois', u'comment', u'1', u''),
        (   49,
            1195605783,
            u'francois',
            u'description',
            u'\r\nProbably we should rebrand Trac to our branding, either nexB, or an OpenALM/TeamALM branding TBD.\r\n\r\nThis would include style sheets, images, and at least a new home page for the wiki. In this home page, we should give ample credit to Trac, and be clear about the fact that this is, at first, very similar to trac, and will evolve over time.\r\n',
            u'\r\nProbably we should rebrand Trac to our branding, either nexB, or an OpenALM/TeamALM branding TBD.\r\n\r\nThis is not about removing the word "trac" everytwere, but to make less proeminent.\r\n\r\nThis would include logo at the top, bottom, and at least a new home page for the wiki.\r\n\r\nAlso there should be a \'Credit\' page for giving credit to Trac.\r\n\r\nMore rebranding planned in #56'),
        (   49,
            1195605783,
            u'francois',
            u'summary',
            u'Rebrand Trac',
            u'Minimal rebranding Trac'),
        (49, 1195605783, u'francois', u'comment', u'3', u''),
        (   50,
            1195605902,
            u'francois',
            u'milestone',
            u'0.01 (Gimli)',
            u'Further milestones'),
        (   50,
            1195605902,
            u'francois',
            u'comment',
            u'1',
            u'not even packaging anytime soon'),
        (41, 1195606153, u'pom', u'cc', u'mjh, philippeo', u'mjh, pom'),
        (41, 1195606153, u'pom', u'comment', u'4', u''),
        (40, 1195606186, u'pom', u'cc', u'mjh, philippeoUI', u'mjh, pom'),
        (40, 1195606186, u'pom', u'comment', u'3', u''),
        (   53,
            1195606193,
            u'francois',
            u'comment',
            u'2',
            u'The changes will be done on this system.\r\n\r\n'),
        (39, 1195606228, u'pom', u'cc', u'mjh, philippeo', u'mjh, pom'),
        (39, 1195606228, u'pom', u'comment', u'3', u''),
        (38, 1195606239, u'pom', u'cc', u'mjh, philippeo', u'mjh, pom'),
        (38, 1195606239, u'pom', u'comment', u'2', u''),
        (37, 1195606245, u'pom', u'cc', u'mjh, philippeo', u'mjh, pom'),
        (37, 1195606245, u'pom', u'comment', u'1', u''),
        (36, 1195606252, u'pom', u'cc', u'mjh, philippeo', u'mjh, pom'),
        (36, 1195606252, u'pom', u'comment', u'6', u''),
        (35, 1195606259, u'pom', u'cc', u'mjh, philippeo', u'mjh, pom'),
        (35, 1195606259, u'pom', u'comment', u'1', u''),
        (   35,
            1195606346,
            u'pom',
            u'comment',
            u'2',
            u'Which screen width should use as a base? '),
        (58, 1195606827, u'francois', u'milestone', u'All', u'0.01 (Gimli)'),
        (58, 1195606827, u'francois', u'comment', u'1', u''),
        (   60,
            1195607384,
            u'pom',
            u'summary',
            u'A voting system',
            u'Support the decision making process'),
        (   60,
            1195607384,
            u'pom',
            u'comment',
            u'1',
            u'A voting system is just one way to elicit decision.\r\nAn example is the axiopole tools'),
        (62, 1195607665, u'francois', u'status', u'new', u'closed'),
        (62, 1195607665, u'francois', u'resolution', u'', u'invalid'),
        (62, 1195607665, u'francois', u'comment', u'1', u''),
        (55, 1195608013, u'francois', u'milestone', u'All', u'0.01 (Gimli)'),
        (55, 1195608013, u'francois', u'comment', u'2', u''),
        (   61,
            1195608128,
            u'francois',
            u'description',
            u'In the action box, there should be a few items leading to further collaboration activities:\r\n- request further details to author\r\n- send/cc: to some people for comments/feedback/updates/details\r\n-  \r\n\r\n\r\n\r\nas configurable to list...',
            u'In the action box, there should be a few items leading to further collaboration activities:\r\n * request further details to author\r\n * send/cc: to some people for comments/feedback/updates/details\r\n *  \r\n\r\n\r\n\r\nas configurable to list...'),
        (61, 1195608128, u'francois', u'comment', u'1', u''),
        (   47,
            1195626638,
            u'mjh',
            u'description',
            u'http://trac-hacks.org/wiki/PollMacro',
            u'The purpose of enabling the PollMacro is to provide a tool for team members to vote on the quality or priority of a requirement.'),
        (47, 1195626638, u'mjh', u'comment', u'1', u''),
        (   51,
            1195626709,
            u'mjh',
            u'description',
            u'try entering a ticket, with severity "Highest - Data integrity issue". It fails ! and you loose the data if you hit "back".\r\n',
            u'try entering a ticket, with severity "Highest - Data integrity issue". It fails ! and you lose the data if you hit "back".\r\n'),
        (   51,
            1195626709,
            u'mjh',
            u'summary',
            u'Entering tickets with "Highest" severity FAILS !!! and loose data',
            u'Entering tickets with "Highest" severity FAILS !!! and you lose data'),
        (51, 1195626709, u'mjh', u'comment', u'3', u''),
        (   58,
            1195626818,
            u'mjh',
            u'summary',
            u'A way to do automatically backtracking between the Wiki and the tickets',
            u'Automatically backtrack between the Wiki and tickets'),
        (58, 1195626818, u'mjh', u'comment', u'2', u''),
        (   36,
            1195626949,
            u'mjh',
            u'description',
            u'',
            u'Once a ticket has been created and user is in ticket review screen, provide a button to go back to where they were (before ticket entry)'),
        (   36,
            1195626949,
            u'mjh',
            u'summary',
            u'Once a ticket has been created and user is in ticket review screen, provide a button to go back to where they were (before ticket entry)',
            u'Enable return from ticket entry to prior screen'),
        (36, 1195626949, u'mjh', u'comment', u'7', u''),
        (   60,
            1195627051,
            u'mjh',
            u'description',
            u'we need a system that enables to:\r\n- make decisions about the requyirements captured\r\n- evaluate the veracity/value of requirements',
            u'we need a system that enables you to:\r\n- make decisions about the requyirements captured\r\n- evaluate the validity/value of requirements'),
        (   60,
            1195627051,
            u'mjh',
            u'summary',
            u'Support the decision making process',
            u'Support a  decision making process'),
        (60, 1195627051, u'mjh', u'comment', u'2', u''),
        (   52,
            1195627133,
            u'mjh',
            u'summary',
            u'Upgrade to 0.11',
            u'Upgrade to Trac 0.11'),
        (52, 1195627133, u'mjh', u'comment', u'1', u''),
        (   70,
            1196126940,
            u'mjh',
            u'description',
            u'I added Tags to some wiki pages.  When you select Tags from the menubar, it displays the correct tags as links, but when you click for the link you get the error "Link not Found".',
            u'I added Tags to some wiki pages.  When you select Tags from the menubar, it displays the correct tags as links, but when you click for the link you get the error "Link not Found". Specific message is:\r\n\r\n{{{\r\nNot Found\r\nThe requested URL /tags/\'Ideas\' was not found on this server.\r\n\r\nApache/1.3.33 Server at office.nexb.us Port 443\r\n}}}\r\n'),
        (70, 1196126940, u'mjh', u'comment', u'1', u''),
        (46, 1196127023, u'mjh', u'component', u'TeamALM', u'Trac plugins'),
        (46, 1196127023, u'mjh', u'comment', u'2', u''),
        (47, 1196127049, u'mjh', u'component', u'TeamALM', u'Trac plugins'),
        (47, 1196127049, u'mjh', u'comment', u'2', u''),
        (   70,
            1196127072,
            u'mjh',
            u'component',
            u'TRAC basic functionality',
            u'Trac plugins'),
        (70, 1196127072, u'mjh', u'comment', u'2', u''),
        (48, 1196127098, u'mjh', u'component', u'TeamALM', u'Trac plugins'),
        (48, 1196127098, u'mjh', u'comment', u'2', u''),
        (   52,
            1196127138,
            u'mjh',
            u'component',
            u'TeamALM',
            u'TRAC basic functionality'),
        (52, 1196127138, u'mjh', u'comment', u'2', u''),
        (   5,
            1190909220,
            u'testuser',
            u'description',
            u'not used if cumbersome:: simple UI',
            u':: '),
        (5, 1190909220, u'testuser', u'users', u'PM', u'DV'),
        (   5,
            1190909220,
            u'testuser',
            u'comment',
            u'',
            u"''Batch update from file test/ticket-13.xls''")],
    [],
    []]
