[   [   (   1,
            u'defect',
            1191377630,
            1190909220,
            u'mycomp',
            None,
            u'mypriority',
            u'me',
            u'anonymous',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'summary before change',
            u'',
            u''),
        (   2,
            u'defect',
            1191377630,
            1190909220,
            u'yourcomp',
            None,
            u'yourpriority',
            u'you',
            u'anonymous2',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'summarybefore change',
            u'',
            u''),
        (   3,
            u'task',
            1190909220,
            1190909220,
            u'hercomp',
            None,
            u'herpriority',
            u'she',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'',
            u'',
            u'')],
    [   (1, u'mycustomfield', u'mycustomfield1'),
        (2, u'mycustomfield', u'customfield2'),
        (3, u'mycustomfield', u'customfield3')],
    [   (1, 1190909220, u'testuser', u'owner', u'somebody', u'me'),
        (1, 1190909220, u'testuser', u'priority', u'major', u'mypriority'),
        (1, 1190909220, u'testuser', u'component', u'component1', u'mycomp'),
        (   1,
            1190909220,
            u'testuser',
            u'mycustomfield',
            None,
            u'mycustomfield1'),
        (   1,
            1190909220,
            u'testuser',
            u'comment',
            u'',
            u'Batch update from file test/with-id-called-id.csv'),
        (2, 1190909220, u'testuser', u'owner', u'somebody2', u'you'),
        (2, 1190909220, u'testuser', u'priority', u'major', u'yourpriority'),
        (   2,
            1190909220,
            u'testuser',
            u'component',
            u'component2',
            u'yourcomp'),
        (2, 1190909220, u'testuser', u'mycustomfield', None, u'customfield2'),
        (   2,
            1190909220,
            u'testuser',
            u'comment',
            u'',
            u'Batch update from file test/with-id-called-id.csv')],
    [(u'priority', u'herpriority', u'6')],
    [(u'hercomp', None, None)]]