[   [   (   1,
            u'defect',
            1190909220,
            1190909220,
            u'',
            None,
            u'major',
            u'ac',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'release > integration, quality & regression',
            u'',
            u''),
        (   2,
            u'defect',
            1190909220,
            1190909220,
            u'',
            None,
            u'major',
            u'fd',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'release > integration, quality & regression',
            u'',
            u''),
        (   3,
            u'defect',
            1190909220,
            1190909220,
            u'',
            None,
            u'major',
            u'gs',
            u'testuser',
            u'',
            u'',
            u'',
            u'new',
            None,
            u'release > integration, quality & regression',
            u'',
            u'')],
    [(1, u'effort', u''), (2, u'effort', u''), (3, u'effort', u'')],
    [],
    [],
    []]