
# PLEASE DO NOT EDIT THIS FILE!
# This file was autogenerated when installing Trac 0.10.4.
#
__default_conf_dir__ = '/usr/share/trac/conf'
__default_templates_dir__ = '/usr/share/trac/templates'
__default_htdocs_dir__ = '/usr/share/trac/htdocs'
__default_wiki_dir__ = '/usr/share/trac/wiki-default'
__default_macros_dir__ = '/usr/share/trac/wiki-macros'
__default_plugins_dir__ = '/usr/share/trac/plugins'

