#!/bin/bash
# openoffice.org  headless server script
#
### BEGIN INIT INFO
# Provides:          openoffice
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: openoffice headless
# Description:       openoffice headless
### END INIT INFO
# 
# Author: Vic Vijayakumar
# Modified by Federico Ch. Tomasczik
#
SOFFICE_PATH="/usr/lib/libreoffice/program/soffice.bin"
PIDFILE=/var/run/openoffice-server.pid

case "$1" in
    start)
    if [ -f $PIDFILE ]; then
      echo "OpenOffice headless server has already started."
      sleep 5
      exit
    fi
      echo "Starting OpenOffice headless server"
      $SOFFICE_PATH --headless --nologo --nofirststartwizard --nodefault --accept="socket,host=localhost,port=8100;urp;StarOffice.ComponentContext" & > /dev/null 2>&1
      echo $! > $PIDFILE
    ;;
    stop)
    if [ -f $PIDFILE ]; then
      echo "Stopping OpenOffice headless server."
      kill -9 `head $PIDFILE`
      rm -f $PIDFILE
      exit
    fi
      echo "Openoffice headless server is not running."
      exit
    ;;
    *)
    echo "Usage: $0 {start|stop}"
    exit 1
esac
exit 0
