// This file was generated by Dashcode from Apple Inc.
// DO NOT EDIT - This file is maintained automatically by Dashcode.
function setupParts() {
    if (setupParts.called) return;
    setupParts.called = true;
    CreateInfoButton('info', { frontID: 'front', foregroundStyle: 'white', backgroundStyle: 'black', onclick: 'showBack' });
    CreateGlassButton('done', { text: 'Done', onclick: 'showFront' });
    CreateShape('topRectangleShape', { rightImageWidth: 12, leftImageWidth: 12 });
    CreateShape('bottomRectangleShape', { rightImageWidth: 12, leftImageWidth: 12 });
    CreateScrollArea('contentarea', { spacing: 11, leftMargin: 11, rightMargin: 7, hasVerticalScrollbar: true, autoHideScrollbars: true, scrollbarMargin: 6, scrollbarDivSize: 18 });
    CreateText('loading-text', { text: 'Loading' });
    CreateText('article-length', { text: 'Article Length' });
    CreateGlassButton('glassbutton', { onclick: 'createNewTicket', text: '+' });
    CreateText('text', { text: 'Trac URL' });
    CreateText('text1', { text: 'User Name' });
    CreateGlassButton('glassbutton1', { onclick: 'viewSource', text: 'Source' });
    CreateGlassButton('glassbutton2', { onclick: 'viewWiki', text: 'Wiki' });
    CreateGlassButton('glassbutton3', { onclick: 'viewTimeline', text: 'Timeline' });
    CreateGlassButton('glassbutton4', { onclick: 'viewRoadmap', text: 'Roadmap' });
}
window.addEventListener('load', setupParts, false);
