=head1 Name

  TicketBackLinksDescription - A trac plugin showing back links in tickets description.


=head1 Description

  TicketBackLinksDescription is a trac plugin that looks for links referring to a ticket
  in wikiformatting and adds them after ticket description.
  It's a modification of BackLinksMacro and SidebarProvider.
  You can also add elements to this plugin easily that will be shown after plugin 
  description.


=head1 Installation

  TicketBackLinksDescription includes a setup.py file for creating python eggs.
  Just run 
  "C<python setup.py bdist_egg>"
