#!/usr/bin/env python

import sys

assert len(sys.argv) == 2, "\n\nusage: %s <trac-environment>\n\nRe-index repository." % sys.argv[0]

from pyndexter import Framework
from trac.env import Environment
from tracreposearch import RepoSource

e = Environment(sys.argv[1])
f = Framework(e.config['repo-search'].get('indexer'))
repo = e.get_repository()
f.add_source(RepoSource(e, f, repo, include=['*.py']))

def logger(context, stream):
    for transition, uri in stream:
        print transition, uri
        yield transition, uri


f.update(logger)
f.close()
