#!/usr/bin/env python

import sys

assert len(sys.argv) == 2, "\n\nusage: %s <trac-environment>\n\nRe-index repository." % sys.argv[0]

from pyndexter import Framework
from trac.env import Environment
from tracreposearch import RepoSource, TracRepoSearchPlugin

e = Environment(sys.argv[1])
s = TracRepoSearchPlugin(e)
s._update_index()
s.framework.close()
