#!/usr/bin/env python

import sys
from trac.env import Environment

assert len(sys.argv) == 2, "\n\nusage: %s <trac-environment>\n\nRe-index repository." % sys.argv[0]

e = Environment(sys.argv[1])
from tracreposearch.indexer import Indexer
indexer = Indexer(e)
