#!/usr/bin/python
# Copyright (C) 2008-2009 NAV CANADA (http://www.navcanada.ca)
# All rights reserved.
#
# This software is licensed as described in the file COPYING, which
# you should have received as part of this distribution.
#
# Author: Mike Stoddart <stoddam@navcanada.ca>

import sys, os, pg, shutil, getpass
from common import *
from config import *

svn_root = ROOT_PATH + os.sep + "svn"
trac_root = ROOT_PATH + os.sep + "trac"

# Check that the password file exists.
check_password_file()

print
username = raw_input("Enter the new user's unix name: ")
print

# Does the user already exist?
exists = user_exists(username)

s = "htpasswd %s %s" % (PASSWORD_FILE, username)
os.system(s)

# Only ask to promote new users.
if exists == False:
    # Confirm the user should be promoted.
    if get_confirmation("Promote user to administrator?"):
	    # Promote the user.
    	promote_user(username)
else:
    print "User %s already exists, skipping promotion" % (username)
