#!/usr/bin/python
# Copyright (C) 2008-2009 NAV CANADA (http://www.navcanada.ca)
# All rights reserved.
#
# This software is licensed as described in the file COPYING, which
# you should have received as part of this distribution.
#
# Author: Mike Stoddart <stoddam@navcanada.ca>

from common import *

# Check that the password file exists.
check_password_file()

print
username = get_unix_username()
print

if len(username) > 0:
	# Promote the user.
	promote_user(username)
else:
	print "Invalid username, exiting"
