#!/usr/bin/python
# Copyright (C) 2008-2009 NAV CANADA (http://www.navcanada.ca)
# All rights reserved.
#
# This software is licensed as described in the file COPYING, which
# you should have received as part of this distribution.
#
# Author: Mike Stoddart <stoddam@navcanada.ca>

import sys, os, pg, shutil, getpass
from config import *
from common import *

svn_root = ROOT_PATH + os.sep + "svn"
trac_root = ROOT_PATH + os.sep + "trac"

# Check that the password file exists.
check_password_file()

# Read the user's unix name to delete.
print
username = get_unix_username()
print

if len(username) == 0:
	print "No user specified, exiting...."
	sys.exit(0)

# Ask for confirmation.
s = "Are you sure you want to delete user " + username + "?"
if get_confirmation(s):
	print
	
	# Delete the user from the password file.
	s = "htpasswd -D " + PASSWORD_FILE + " " + username	
	os.system(s)
	
	projects = get_project_list()
	for project_name in projects:
		# Verify the project name.
		if len(project_name) > 0:
			# Demote the user.
			s = "trac-admin " + os.sep + ROOT_PATH + os.sep + "trac" + os.sep + \
				project_name + " permission remove " + username + " TRAC_ADMIN"
			os.system(s)

else:
	print "User " + username + " will not be deleted, exiting...."
