#!/usr/bin/python
# Copyright (C) 2008-2009 NAV CANADA (http://www.navcanada.ca)
# All rights reserved.
#
# This software is licensed as described in the file COPYING, which
# you should have received as part of this distribution.
#
# Author: Mike Stoddart <stoddam@navcanada.ca>

import os
from common import *
from config import *

def mkdir(path):
	# Create the top directory
	if not os.path.isdir(path):
		print "\tCreating directory " + path
		os.mkdir(path)
	
		# Set ownership to apache.
		set_ownership(path)
	else:
		print "\t" + path + " already exists, ignoring"

def create_trac_environment(trac_root):
	print "Creating directory for Trac environments in %s" % (trac_root)

	# Create the root directory.
	mkdir(trac_root)

def create_svn_repo(svn_root):
	print "Creating directory for Subversion repositories in %s" % (svn_root)

	mkdir(svn_root)

def create_srv(srv_root):
	print "Creating server directory in %s" % (srv_root)

	# Create the root directory.
	mkdir(srv_root)
	
	# Create the password file. Delete it if it already exists.
	create_password_file()


svn_root = ROOT_PATH + os.sep + "svn"
trac_root = ROOT_PATH + os.sep + "trac"

print
create_srv(ROOT_PATH)
create_trac_environment(trac_root)
create_svn_repo(svn_root)
print
