################################################## 
# SentinelService_services.py 
# generated by ZSI.generate.wsdl2python
##################################################


from SentinelService_services_types import *
import urlparse, types
from ZSI.TCcompound import ComplexType, Struct
from ZSI import client
import ZSI

# Locator
class SentinelServiceLocator:
    SentinelEndpoint_address = "https://sentinelws.msu.edu/sentinel/service"
    def getSentinelEndpointAddress(self):
        return SentinelServiceLocator.SentinelEndpoint_address
    def getSentinelEndpoint(self, url=None, **kw):
        return SentinelEndpointBindingSOAP(url or SentinelServiceLocator.SentinelEndpoint_address, **kw)

# Methods
class SentinelEndpointBindingSOAP:
    def __init__(self, url, **kw):
        kw.setdefault("readerclass", None)
        kw.setdefault("writerclass", None)
        # no resource properties
        self.binding = client.Binding(url=url, **kw)
        # no ws-addressing

    # op: getCredential
    def getCredential(self, request):
        if isinstance(request, SentinelEndpoint_getCredential) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="", **kw)
        # no output wsaction
        response = self.binding.Receive(SentinelEndpoint_getCredentialResponse.typecode)
        return response

    # op: getIdentity
    def getIdentity(self, request):
        if isinstance(request, SentinelEndpoint_getIdentity) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="", **kw)
        # no output wsaction
        response = self.binding.Receive(SentinelEndpoint_getIdentityResponse.typecode)
        return response

SentinelEndpoint_getCredential = ns0.getCredential_Dec().pyclass

SentinelEndpoint_getCredentialResponse = ns0.getCredentialResponse_Dec().pyclass

SentinelEndpoint_getIdentity = ns0.getIdentity_Dec().pyclass

SentinelEndpoint_getIdentityResponse = ns0.getIdentityResponse_Dec().pyclass
